### ISSUE TITLE
undefined has no properties

### ISSUE THREAD

**Issue by roweldeguzman** [videojs/videojs-contrib-hls#1206] opened 2017-07-24 10:07 UTC
VideoJs version 6.2.0
Videojs-contrib-hls.js version 5.8.2

![video-js-hls-error](https://user-images.githubusercontent.com/8720937/28518523-bf64a538-709a-11e7-8fdf-070278c4d99c.png)

**Comment by gesinger** [comment] 2017-07-24 21:22
Hey @roweldeguzman , thanks for the issue, however, it is hard to debug without a sample page and information about the issue. Would you be able to provide a sample page showing the issue using our [starter template](http://jsbin.com/vokipos/8/edit?html,console,output), as well as fill out the information in our [issue template](https://github.com/videojs/videojs-contrib-hls/issues/new)? Thank you.

**Comment by roweldeguzman** [comment] 2017-07-26 07:08
hi @gesinger ,

seems this error only occur when in live broadcasting. VOD has no error showing.

**Comment by gesinger** [comment] 2017-07-26 20:53
Do you have a link to your live stream @roweldeguzman , and steps to reproduce? Thanks.

**Comment by roweldeguzman** [comment] 2017-07-27 01:46
Hi @gesinger ,

here is jsbin [http://jsbin.com/viwoga/edit?html,output](url) to show the error in console. for Live just wait a few seconds after you play the video.

**Comment by mjneil** [comment] 2017-07-27 15:15
It looks like your stream has audio that is unsupported by chrome
`window.MediaSource.isTypeSupported('video/mp4; codecs="avc1.42001f,mp4a.40.34"')`
which prompts contrib-hls to blacklist the playlist, but since you only have a single variant, there are no enabled playlists for the selector to pick from. #1207 would fix the error from occuring, but audio will continue to not work unless you update your encoder settings

**Comment by mjneil** [comment] 2017-10-19 19:03
You should no longer see the undefined error in v5.12.0. Closing this issue for now, please re-open or submit a new one if you continue to experience issues.

**Closed by mjneil** 2017-10-19 19:03 UTC
Labels: needs:info
