### ISSUE TITLE
Level Switcher

### ISSUE THREAD

**Issue by clzola** [videojs/videojs-contrib-hls#739] opened 2016-06-10 09:53 UTC
How do I add level switcher (240p, 720p, 1080p...) and also change levels?

**Comment by gkatsev** [comment] 2016-06-10 15:20
There's the new ["representations"](https://github.com/videojs/videojs-contrib-hls#hlsrepresentations) API that you can use to limit contrib-hls to a certain subset of playlists.
A menu can be made using videojs's MenuButton component.

**Comment by piotr-cz** [comment] 2016-06-11 17:35
Is it available in v3.1.0? It doesn't seem that the `player.hls.representations` function is defined

**Comment by clzola** [comment] 2016-06-12 13:55
@gkatsev For example lets have 240p, 360p,480p, 720p, 1080p.
If I want to show video 720p, i should iterate over all representations and for each that is <= 720p I should call enabled(true) otherwise enabled(false).

Or for 360p, i should call for all that are <= 360 enabled(true) otherwise enabled(false)

Or should I call enabled(true) only for that particular level and calling enabled(false) for others?

**Comment by gkatsev** [comment] 2016-06-12 16:18
@clzola it depends on how wide you want each item to be. For example, you could have several 720p resolution streams but with different bitrates. So, when a user selects `720p`, you'll enable all of those by calling `enabled(true)` and then disable the rest with `enabled(false)`.
You could also widen the rage by say including 540p streams when you want to show 720p just so that the video will be less likely to buffer, so, it'll be possible for contrib-hls to do rendition switching a bit.
It all depends on how wide a band you want to define as "720p".

**Comment by gkatsev** [comment] 2016-06-12 16:21
@piotr-cz it *should* be available. If you go to our [live example](http://videojs.github.io/videojs-contrib-hls/) and type `player.hls.representations()` into the console, you should see it give you back an array with several items.

**Comment by gkatsev** [comment] 2016-06-12 16:22
Going to close this but we can definitely continue the discussion here and if we find an issue we can either re-open or open a new issue.

**Closed by gkatsev** 2016-06-12 16:22 UTC

**Comment by piotr-cz** [comment] 2016-06-12 18:34
True, thanks for checking.

**Comment by piotr-cz** [comment] 2016-06-12 18:55
Somehow the `renditionSelectionMixin` which sets representations on the hlsHandler is not invoked in my app.
Probably because there is no audio in the stream info and I'm streaming from live cams, [this code block](https://github.com/videojs/videojs-contrib-hls/blob/v3.1.0/src/videojs-contrib-hls.js#L429-L482) doesn't run

**Comment by talk2cerlin** [comment] 2016-07-26 05:31
is there any resolution switching button??

**Comment by adityaj221** [comment] 2016-08-26 09:57
When I try to run player.hls.representation() on Safari. It throws an error 

`TypeError: undefined is not an object (evaluating 'player.hls.representations')`

![screen shot 2016-08-26 at 5 51 40 pm](https://cloud.githubusercontent.com/assets/11585307/18001641/73883f4c-6bb6-11e6-8817-9520e9e2c924.png)


Can anyone help me on this.

**Comment by piotr-cz** [comment] 2016-08-26 10:05
@adityaj221 Have you tried with the latest release of _videojs-contrib-hls_?
Also, does your stream contain audio?

**Comment by adityaj221** [comment] 2016-08-26 10:26
@piotr-cz Yes I'm using the latest version of <i>videojs-contrib-hls</i>

Also, the above screenshot is from the [live example](http://videojs.github.io/videojs-contrib-hls/)

Same thing is happening on my code as well. I'm using:

videojs: 5.11.6
videojs-contrib-hls: 3.5.3

**Comment by gkatsev** [comment] 2016-08-26 15:57
Safari doesn't run contrib-hls, we let the native HLS implementation take over.

**Comment by adityaj221** [comment] 2016-08-29 03:50
@gkatsev - Is there a way in the native HLS implementation to set the representations in that case.?

**Comment by gkatsev** [comment] 2016-08-29 03:57
Unfortunately, there isn't any way to ask Safari to switch to a specific rendition.
We'll be investigating soon (not sure how soon) being able to force contrib-hls on on browsers that we previously use native HLS implementations but we don't have that functionality easily exposed right now.

**Comment by adityaj221** [comment] 2016-08-29 03:58
Thanks for the information.

**Comment by adityaj221** [comment] 2016-08-29 04:01
@gkatsev - I've seen this[link](http://dailymotion.github.io/hls.js/demo/) by hls.js and they have the manual switching implemented.

**Comment by gkatsev** [comment] 2016-08-29 04:20
If it works on Safari, it's because they aren't relying on native behavior at the moment.

**Comment by AdamTyler** [comment] 2016-09-13 22:10
@gkatsev is there a quick and dirty workaround for the meantime to force Safari to use contrib-hls?

I tried making `supportsNativeHls` return false but that didn't seem to do the trick.

**Comment by codex-corp** [comment] 2017-07-04 21:16
Here my solution to add level switcher menu, it's not ready 100% but it's working fine for me 👍

>     "video.js": "^5.19.2",
>     "videojs-contrib-hls": "^5.4.1",
>     "videojs-contrib-quality-levels": "^2.0.3",

```js
/**
 * Author (c) Hany alsamman
 * Licensed under the Apache-2.0 license.
 **/

(function () {
    /* jshint eqnull: true*/
    /* global require */
    'use strict';
    var videojs = null;

    if (typeof window.videojs === 'undefined' && typeof require === 'function') {
        videojs = require('video.js');
    } else {
        videojs = window.videojs;
    }

    (function (window, videojs) {
        'use strict';

        var defaults = {};

        /**
         * Return MenuButton's MenuItems.
         *
         * @method MenuButton.getItems
         * @return MenuItem[]
         */
        var MenuButton = videojs.getComponent('MenuButton');

        /**
         * Set current level.
         * This provides interface to either Player tech.
         *
         * @method setLevel
         * @param  {Number} level
         * @return Levels[]
         */
        videojs.getComponent('Player').prototype.setLevel = function (level) {
            var current_list = player.hls.playlists.master.playlists;

            player.hls.representations().forEach(function(rep) {
                if (rep.bandwidth === level) {
                    // player.handleTechWaiting_();
                    current_list.forEach(function(list,index) {
                        if(list.attributes.BANDWIDTH === level){
                            // console.log(player.hls.playlists.master.playlists[index]);
                            player.hls.playlists.media(player.hls.playlists.master.playlists[index]);
                        }
                    });
                    rep.enabled(true);
                    // player.hls.bandwidth = level;
                } else {
                    rep.enabled(false);
                }
            });
            player.handleTechPlaying_();
            // this.getTech().setLevel(level);
        };

        var MenuItem = videojs.getComponent('MenuItem');

        videojs.MenuItemTest = videojs.extend(MenuItem, {

            constructor: function (player, options, onClickListener) {
                this.onClickListener = onClickListener;

                // Call the parent constructor
                MenuItem.call(this, player, options);
                this.on('click', this.onClick);
                this.on('touchstart', this.onClick);

            },
            onClick: function () {
                this.onClickListener(this);
                var selected = this.options_.el.value;
                console.log(this.options_.el.value);
                player.setLevel(selected);
            }
        });

        /**
         * LevelsMenuButton
         */
        videojs.levelsMenuButton = videojs.extend(MenuButton, {

            className: 'vjs-menu-button-levels ',

            init: function (player, options) {

                videojs.getComponent('MenuButton').call(this, player, options);

                this.controlText('Quality');

                var staticLabel = document.createElement('span');
                staticLabel.classList.add('vjs-levels-button-staticlabel');
                this.el().appendChild(staticLabel);

            },

            createItems: function () {

                var component = this;
                var player = component.player();
                var fetch_levels = player.qualityLevels();
                console.log(fetch_levels);
                var levels = fetch_levels.levels_;

                var item;
                var menuItems = [];

                if (!levels.length) {
                    return [];
                }

                // Prepend levels with 'Auto' item
                levels = [{
                    name: 'Auto',
                    index: -1
                }].concat(levels);

                var onClickUnselectOthers = function (clickedItem) {
                    menuItems.map(function (item) {
                        if ($(item.el()).hasClass('vjs-selected')) {
                            $(item.el()).removeClass('vjs-selected');
                        }
                    });
                    $(clickedItem.el()).addClass('vjs-selected');
                };

                return levels.map(function (level, index) {

                    // Select a label based on available information
                    // name and height are optional in manifest
                    var levelName;

                    if (level.name) {
                        levelName = level.name;
                    } else if (level.height) {
                        levelName = level.height + 'p';
                    } else {
                        //levelName = Math.round(level.bitrate / 1000) + ' Kbps';
                        if (level.bitrate) {
                            levelName = (Math.round(level.bitrate / 1024) + 'kb');
                        } else {
                            return null;
                        }
                    }

                    item = new videojs.MenuItemTest(player, {
                        el: videojs.getComponent('Component').prototype.createEl('li', this, {
                            label: levelName,
                            value: level.bitrate,
                            class: 'vjs-menu-item'
                            //tabIndex: 0,
                        })
                    }, onClickUnselectOthers);

                    /**
                     * Store MenuButton's MenuItems.
                     * @return object
                     */
                    menuItems.push(item);

                    if (level.name === 'Auto') {
                        $(item.el()).addClass('vjs-selected');
                    }
                    $(item.el()).html(levelName);

                    return item;
                });
            }

        });

        // register the plugin
        videojs.plugin('levels', function (options) {

            var settings = videojs.mergeOptions(defaults, options);
            var player = this;
            var button = null;

            player.on('loadedmetadata', function (evt) {
                if (button) {
                    button.dispose();
                }
                button = new videojs.levelsMenuButton(player, settings);
                button.el().classList.add('vjs-menu-button-levels');

                player.controlBar.addChild(button);
            });
        });

    })(window, videojs);

})();

```

**Comment by blazarev** [comment] 2017-07-14 08:24
not sure that you really need in this case manually select playlist through player.hls.playlists.media call. Seems to be enough to disable all representations except selected - then default adaptive algorithm will have no choice, except one enabled representation.

**Comment by chianhsieh** [comment] 2017-07-26 14:35
Thank you @codex-corp. Your solution is great.

But when I selected a targeted resolution and selected back to "Auto", the auto does not work. 
Do you have any idea to make it work?

Many thanks.

**Comment by chianhsieh** [comment] 2017-07-26 15:51
Thank you  @codex-corp, your method is great.

But I got a exception when I changed the resolution again and again.
For example, if my list has 2 resolutions which are A and B.
If I selected A and then B, and selected A and then B again, the exception will be threw as the following:

`VIDEOJS: ERROR: TypeError: Cannot read property 'playlist' of undefined

And the root cause is this line
`rep.enabled(false)`

Do you have any idea on this exception?
Many Thanks.
`

**Comment by codex-corp** [comment] 2017-07-26 19:53
@dmlap hi master, could you help to make this code better.
