### ISSUE TITLE
How to log which segment is currently playing.

### ISSUE THREAD

**Issue by rahulsingh9096806080** [videojs/videojs-contrib-hls#1209] opened 2017-07-25 06:43 UTC
I want to log the segment info of the currently playing video

**Comment by tchakabam** [comment] 2017-07-25 10:21
https://github.com/videojs/videojs-contrib-hls#segment-metadata

**Comment by mjneil** [comment] 2017-07-25 15:39
Closing this as it is a duplicate of #1208. Please continue discussion in #1208

**Closed by mjneil** 2017-07-25 15:39 UTC
