### ISSUE TITLE
can't play live hls on android #953

### ISSUE THREAD

**Issue by kiscoman** [videojs/videojs-contrib-hls#1162] opened 2017-06-13 11:06 UTC
Hello,

the issue 953 was closed, but I´m having the same problem, HLS seems that doesn´t work in Android. Is easy to check it, just use the developer tools form Chrome, set the equipment to any of the android devices that comes by default, and go to [http://jsbin.com/vokipos/8/edit?html,output](url)
That video doesn´t work with android, but works with any other device as Ipad.

**Comment by gesinger** [comment] 2017-06-13 14:21
Hey @kiscoman , thanks for reporting, but Chrome's device toolbar is limited in its functionality. While it is often helpful to test certain aspects of these devices, it has many limitations ( https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports#limitations ). Is this the feature you are using, and would you be able to test on a physical device? Thanks.

**Comment by kiscoman** [comment] 2017-06-13 14:49
Hello, 
Yes, I tested the template in a Real device and works, but not my web page.
I put exactly the same scripts but with my own hls stream, and is funny because works when the device use mobile data, and doesn't work using WiFi.

**Comment by gesinger** [comment] 2017-06-15 16:38
That seems to be correct behavior, that a real device would work but Chrome's device toolbar would not always be expected to work.

As for the mobile data vs wifi, would you be able to explain that case a bit more? Are you using a real device and changing the network during streaming, or if you start up on mobile data vs wifi the behavior is different? Does the player say anything specific? Thanks.

**Comment by kiscoman** [comment] 2017-06-15 18:28
Hello again. 
If I open the web page where the streaming is using mobile data it works, but with using wifi not. 
Is something related with settings the source. If I change to WiFi once I see the video keeps working, but if I load Another not. 
When doesn't work te he player says error code 4.
Using the debug with the device connected to a laptop I can see the error code 4, but any other difference in the behaviour except that. The m3u8 file is downloaded in the same way, and Take more or less the same time.

**Comment by gesinger** [comment] 2017-07-07 22:43
Do you see that happening with the default template https://github.com/videojs/videojs-contrib-hls/issues/url ?

**Comment by piotr-cz** [comment] 2017-07-12 13:15
I'm having similar issue:

Chrome 59M on Android adds a header `Range:bytes=0-` every time when requesting a playlist m3u8 file.
Server responds with 206 Partial content response, but chrome doesn't download response body and player is stuck at the loading state forever.

Chrome on desktop doesn't add this header by default but when I enforce it, response body isn't downloaded as well,

To reproduce:
```js
fetch('http://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8', {
  headers: {range: 'bytes=0-'}
})
```

**Comment by piotr-cz** [comment] 2017-07-12 13:56
Well, in my case this might be a problem with Flussonic server and CORS configuration.
It responds with playlist body to OPTIONS request and afterwards with an empty response body to GET request when triggering fetch manually (I can see just second request when using video.js).

When running fetch in Firefox, both requests contain full body with playlist.

Anyway I wonder why request to bipbop playlist doesn't get any response body, event that CORS look fine

**Comment by thecotne** [comment] 2017-07-13 06:55
android chrome has native support for hls streams so you need to test it with raw video tag
if it does not play it's problem with server not player

i had same issue updating Flussonic to latest version solved issue

**Comment by thecotne** [comment] 2017-07-13 08:31
4.6.16 (latest)

**Comment by piotr-cz** [comment] 2017-07-13 08:40
Thank you, will check it out

**Comment by thecotne** [comment] 2017-07-14 18:35
@piotr-cz any progress?

**Comment by piotr-cz** [comment] 2017-07-15 07:58
@thecotne Flussonic server is being managed by other company and they decided to update when new release comes up which should be in about two weeks - and they responded with _It works for me_ type of reply.
Unfortunately when streams don't work they tend to blame player.

**Comment by thecotne** [comment] 2017-07-15 08:05
you need to make example with raw video tag with there .m3u8 url and apple
example stream and show them that in android chrome apple hls example works
and old Flussonic not

when my player did not work everyone blamed player including me but then i
tested native support with video tag

**Comment by arski** [comment] 2017-11-18 16:33
@piotr-cz @thecotne I read through the thread multiple times but still can't quite figure out what to do.. I'm having a similar issue with my m3u8, Chrome on Android returns a 200 for the request, but nothing in the body, so the player is just stalled.. Works on FF/Android, Chrome/Desktop etc.

I know on Safari on OSX, when there is an issue with the CORS headers, the request returns a 403, which is.. fine, OK, different problem. But the fact that here it's a 200 (so seemingly all good) but then nothing in the body is a bit weird.

Any suggestions on how to debug this on server side?

**Comment by piotr-cz** [comment] 2017-11-18 19:36
@arski For us the issue was that Chrome on android changed CORS behavior for HLS streams.
We had to update media server (Flussonic) where they introduced correct CORS handling.

I'm afraid that I can't help you more as I can't reproduce the issue. Get in touch with your media server support. It's been almost 6 months since Chrome v59 for Android has been released and the must have a solution by now.

**Comment by Sathishchary** [comment] 2017-11-29 12:18
Hi, I am also facing the same kind of problem. My m3u8 files are playing correctly with videojs contrib hls in computer, and ipad, iphone and etc, and those same videos are not playing in android ( checked in marshmallow version). Its just showing the videolength time as '0:00', and stopped playing, I am using latest videojs contrib hls version
versions:
videojs - 6.4.0
videojs contrib-hls: 5.12.2
used flash also: videojs-flash: 2.0.1
m3u8 url : https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
below hls example is perfectly working in android.
http://videojs.github.io/videojs-contrib-hls/
can any one help me on this
thanks

**Comment by forbesjo** [comment] 2018-03-16 17:58
This issue seems to have a combination of different backend related issues going on, if anyone is still having a problem with their stream please open a new issue.

**Closed by forbesjo** 2018-03-16 17:58 UTC
Labels: needs:info

**Comment by coolicer** [comment] 2018-03-28 02:25
Same problem in chrome simulator when use hls live stream.
