### ISSUE TITLE
Changing source URL leads to closed captioning track duplicate

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-hls#890] opened 2016-11-02 22:32 UTC
## Description
When a user changes source HLS URL with closed captioning, the player creates a duplicate CC track and shows it in UI.

## Sources
http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8

## Steps to reproduce
Open following URL:
http://www.w3schools.com/code/tryit.asp?filename=F0EFFPUMR91Z

1. Start playback, click CC button, notice that there is single CC track
2. Click "Set URL" button, which basically just changes source URL via `player.src` call. I use the same URL in my example for simplicity.
3. click CC button again and notice that there are 2 CC tracks now (duplicate was created)

### Expected
The duplicate should not be created

### Error output
No error output

### Additional information
The bug can be reproduced only on HLS stream with closed captions. I tried to dig into the issue. It's related to the mechanism of preserving CC tracks between URL switching, but it happens with HLS only.
Possible relevant code: https://github.com/videojs/video.js/blob/ae3e27788db2ad2386f7194ffd2ac1aa9321f74e/src/js/player.js#L749

I found a workaround, which does not really fix the issue.
I simply clear text tracks list once new `src` is about to be set (via wrapping player's `src` call):
```
player.src = _.wrap(this.player.src, function(fn) {
            // `this` is `player` in this case
            this.techCall_('clearTracks', ['text']);
            var args = _.rest(arguments, 1);
            return fn.apply(this, args);
});
```

### videojs-contrib-hls version
videojs-contrib-hls 3.6.6

### videojs version
video.js 5.11.9

### Browsers
Chrome 54.0.2840.71, but I'm pretty sure the bug can be repeated in any browser

### Platforms
I tested on OSX, but I'm pretty sure a bug can be repeated in any platform

**Comment by dmlap** [comment] 2016-11-02 22:43
Good find and thank you for the running example!

**Comment by dmlap** [comment] 2016-11-07 17:29
@imbcmdth has proposed https://github.com/videojs/video.js/pull/3736 to address this.

**Comment by gesinger** [comment] 2017-01-20 20:23
https://github.com/videojs/video.js/pull/3736 has since been merged into Video.js. @askaliuk , have you had a chance to give it a shot? Thanks again!

**Comment by askaliuk** [comment] 2017-01-20 20:30
@gesinger I didn't try new version. I will as soon as I can.

**Comment by gesinger** [comment] 2017-03-21 19:25
Confirmed in http://jsbin.com/sacizecaqe/3/edit?html,output . Thanks again for reporting the issue @askaliuk , and let us know if you encounter any more issues.

**Closed** 2017-03-21 19:25 UTC
Labels: confirmed
