### ISSUE TITLE
stucks for very little time every 10-40 seconds.

### ISSUE THREAD

**Issue by fakirpic** [videojs/videojs-contrib-hls#943] opened 2016-12-26 20:46 UTC
Hi videojs hls works good on ios native player but on pc , it stucks for very little time always

```
    var player = videojs('video', {
        loadingSpinner: true,
        autoplay: true,
        sources: [{
            type: "application/x-mpegURL",
            src: m3u8link
        }]
    }, function() {
        console.log('go go!');
        this.on('ended', function() {
            player.src({
                src: m3u8link,
                type: 'application/x-mpegURL'
            });
            player.play();
        });
        this.on('error', function() {
            player.src({
                src: m3u8link,
                type: 'application/x-mpegURL'
            });
            player.play();
        });
    });

```

as example m3u8 generated by ffmpeg

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:1657
#EXTINF:0.900000,
../ts/stream-63556870-1657.ts
#EXTINF:2.666667,
../ts/stream-63556870-1658.ts
#EXTINF:0.833333,
../ts/stream-63556870-1659.ts
#EXTINF:2.966667,
../ts/stream-63556870-1660.ts
#EXTINF:2.600000,
../ts/stream-63556870-1661.ts

```

**Comment by gesinger** [comment] 2017-01-19 22:21
Hey @fakirpic , it sounds like there might be gaps in the stream. This could be due to a variety of reasons. Would you be able to put together a reduced test case on JSBin using [this template](http://jsbin.com/liwecukasi/edit?html,output)? Thank you!

**Comment by fakirpic** [comment] 2017-01-22 23:07
@gesinger its not possible,my stream can't be watched over different domains

**Comment by fakirpic** [comment] 2017-01-22 23:17
i tried that template on my server it fails to load second hls and giving these errors.

VIDEOJS: WARN: Problem encountered with the current HLS playlist. No suitable alternatives found.
_logType @ log.js:79

VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the media download to fail part-way. MediaError {code: 2, message: "A network error caused the media download to fail part-way."}
.

ios can play without problems.
my videojs player can play but it stucks every time but i dont see any network problem

**Comment by gesinger** [comment] 2017-01-23 15:42
@fakirpic , usually that error indicates that there is a problem downloading the playlist or segment from the server (usually this means the server is having a problem or is missing the information).

If you have a way to provide a sample stream that demonstrates this issue, we can check to see what might be going on. But without the stream itself, we can't reproduce it. If the problem of different domains is due to a lack of CORS, we might be able to proxy a CORS header to test.

**Comment by gesinger** [comment] 2017-01-31 22:19
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.0.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Closed by gesinger** 2017-01-31 22:19 UTC
Labels: needsinfo
