### ISSUE TITLE
VideoJS waiting fron an HLS source?

### ISSUE THREAD

**Issue by Shamaon** [videojs/videojs-contrib-hls#1244] opened 2017-08-28 15:50 UTC
Hello everyone, 

i am currently building a streaming platform which uses HLS  for live event streaming.

I have been looking around the web for an answer but i cant find anything that points me in the right direction, which makes me wonder if anyone has ever had this issue before.

So im sending a rtmp stream to an encoding server, which converts this stream into HLS segments which are then requested by a video js player on an external website.  The issue i have is that i dont want my users to keep refreshing the page until a video file is found by the VideoJS player.

 Before the first HLS segment is created and found by the VideoJS player the player will display ""The media could not be loaded, either because the server or network failed or because the format is not supported"".

I just want the player to autoplay the video when it sees that the first segment was created on my server.

i hope the question was kinda clear and that someone can help me out.

cheers!

**Comment by mjneil** [comment] 2017-08-31 19:24
If I understand correctly, the problem is that you have a page that users can visit to tune into your live stream, but an error is displayed when trying to visit the page before you have started the rtmp stream?

One suggestion if possible is to have your rtmp stream running just serving a static clip on loop until your actual content starts.
Another idea could be to not set the source in the player and have a custom script running on your page that pings the server and when it sees that the stream has started, set the source in the player and play.

**Comment by Shamaon** [comment] 2017-10-04 15:24
Hey, thanks for the reply, both ideas are nice but i did not have time to try them both. Ill let you know when if i ever get to try them out!

**Comment by gesinger** [comment] 2018-03-13 21:41
Closing as answered for now. If you're still having trouble, please let us know. Thank you.

**Closed by gesinger** 2018-03-13 21:41 UTC
