### ISSUE TITLE
Http request to same segment/packet in loop - low speed connection

### ISSUE THREAD

**Issue by mpsiva89** [videojs/videojs-contrib-hls#920] opened 2016-11-18 06:55 UTC
When network speed is low, I see repetitive same segment/packet request in loop. 

Ex:
![bug](https://cloud.githubusercontent.com/assets/2209826/20421325/28ae4ba0-ad89-11e6-8560-867826947d41.jpg)

Above image is just for example. After particular time, the request is made again for the same "ts segment" or "ts packet". And the time were same for all the requests, as you can see in the image.

## Steps to reproduce
I am not able to reproduce, when the connection is good. The same video file when played with JWPlayer, it completed retrieving the first segment and went on to the next segment. 
VideoJs though made same requests repetitively. 

### Expected
It should move on to retrieve the next segment, after successful rending for first segment (not sure what's happening here). 

### Error output
No errors in console

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.0.2

### videojs version
what version of videojs does this occur with?
video.js 5.10.2

### Browsers
* Happened while tested in chrome.

**Comment by mjneil** [comment] 2016-11-21 15:12
Can you try using the latest version of videojs-contrib-hls and see if your issue still occurs?

**Comment by gesinger** [comment] 2017-02-02 15:21
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.1.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Since it requires network speed to be low, it's also ok to provide throttling settings for the Chrome dev tools in order to reproduce. Thank you.

**Closed by gesinger** 2017-02-02 15:21 UTC
Labels: needsinfo
