### ISSUE TITLE
Contunious switch to fullscreen and normal mode causes hls  video to stop

### ISSUE THREAD

**Issue by sriman** [videojs/videojs-contrib-hls#798] opened 2016-07-27 05:45 UTC
## Description
Briefly describe the issue.
Continuous switch to fullscreen and normal mode causes video to stop

## Sources
http://videojs.github.io/videojs-contrib-hls/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the hls video
2. go to fullscreen mode and hit escape
3. continue this process 4 or 5 times
4. video is stopped and wont play again
5. recreated the issue and  attached the recorded screen video

### Expected
Video should play smoothly even though we switch to fullscreen back and forth.

### Error output
Video stops and wont play again automatically 

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs version
what version of videojs does this occur with?
5.10

### Browsers
Chrome 51.0

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Mac OS X Capitan, 10.11.3
[fullscreenissue.mp4 (1).zip](https://github.com/videojs/videojs-contrib-hls/files/385365/fullscreenissue.mp4.1.zip)
<img width="1280" alt="screen shot 2016-07-27 at 12 55 32 am" src="https://cloud.githubusercontent.com/assets/2287197/17165067/46f87aa6-53eb-11e6-91f9-93a4bc119c29.png">

**Comment by BrandonOCasey** [comment] 2016-07-27 14:56
we will have to find out if this is an HLS issue or a general video.js issue. https://github.com/videojs/video.js/issues/3466

**Comment by sriman** [comment] 2016-07-27 18:25
yeah need to have fix for this, coz we are daily reported by our consumers saying timeout issue, I can recreate the issue anytime on any video of hls in video js open source player.

**Comment by mkhazov** [comment] 2016-07-28 13:15
Probably the same as #765

**Comment by sweissman59** [comment] 2016-08-10 19:21
I've been digging through the videojs-contrib-hls code this morning, and I'm wondering if this issue might have to do with calling pause() on the segment-loader while the segment-loader's state is 'WAITING'.

When switching into fullscreen and back out repeatedly, the master-playlist-controller is getting 'mediachanging' and 'mediachange' events from the masterPlaylistLoader, and those event handlers are calling pause(), abort(), playlist(), and load() on the mainSegmentLoader.

It looks like if that pause() call happens while the segment-loader's state is 'WAITING', then abort() is called while it's both paused and waiting, so the internal abort_() call happens, and the state remains 'WAITING' because it's paused.  The playlist() call similarly doesn't change the state because paused() is true, and so load() is called while the state is still 'WAITING', meaning it returns before calling fillBuffer_().

One way or another it seems like the segment-loader's state shouldn't be 'WAITING' after an abort() call.  I'm going to continue messing around and see if I can fix the issue, but I'm pretty new to using this plugin, so I might be missing other ramifications of that 'WAITING' state.

**Comment by gkatsev** [comment] 2016-08-15 20:35
If the issue is because of clearing the buffer when switching to fullscreen on the `fullscreenchange` event, we possibly would want to debounce the event so that if we get several fullscreenchange` events, we won't try clearing the buffer on each one.

**Comment by dmlap** [comment] 2016-08-16 22:22
Should be fixed in 3.5.1.

**Closed by dmlap** 2016-08-16 22:22 UTC
Labels: bug
