### ISSUE TITLE
MediaError 3 in Safari 10.1 using HLS and VTT Subtitles

### ISSUE THREAD

**Issue by shinefour** [videojs/videojs-contrib-hls#1203] opened 2017-07-20 11:55 UTC
## Description
I want to use a player with HLS and VTT as Subtitles-Track.

## Sources
http://ext.globalstudio.es/player/hls_vtt.html

## Steps to reproduce
create player with video-tag:
```
<video id="my-video1" class="video-js" controls preload="auto" width="640" height="264" data-setup="{}">
    <source src="//xyz.com/xyz.csmil/master.m3u8" type="application/x-mpegURL">
    <track src="/subtitles.vtt" kind="subtitles" srclang="es" label="Spanish (Spain)">
</video>
```

Use Safari on OSX
open the source example. The first video does work in chrome but not in Safari 10.1

### Expected
I expect the video to play with subtitles in the foreground

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

VIDEOJS: (4)
"ERROR:"
"(CODE:3 MEDIA_ERR_DECODE)"
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

### videojs-contrib-hls version
videojs-contrib-hls 5.8.2

### videojs version
video.js 6.2.0

### Browsers
Safari 10.1
*

### Platforms
OSX 10.11.6
*

### Other Plugins
NONE
*

### Other JavaScript
NONE
*

**Comment by gesinger** [comment] 2017-07-20 15:05
Thanks for the sample @shinefour . One thing that may contribute to the issue is that I saw there are CORS errors being logged to the console for both Chrome and Safari. Here's an example from Chrome:

```
Text track from origin 'http://vod-origin.globalmest.net' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://ext.globalstudio.es' is therefore not allowed access.
XMLHttpRequest cannot load http://vod-origin.globalmest.net/8RK9QO/RNeL5y/Q4ZlLR.vtt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ext.globalstudio.es' is therefore not allowed access. The response had HTTP status code 404.
```

Another thing to note is that Safari uses native playback by default, but seems to be able to play the m3u8 if loaded directly into the browser. It's possible that the CORS errors are preventing Safari from playing back the content.

Please try adding CORS support, giving it another shot, and letting us know. Thanks.

**Comment by shinefour** [comment] 2017-07-21 11:11
Thanks for the feedback.
I've moved the subtitle file to the same domain. The origin error does not appear anymore.
I don't see any errors en chrome anymore, but the problem persists.

**Comment by hazarartuner** [comment] 2017-07-24 07:10
I'm getting same issue too. I noticed that in your sample, track files look like embedded in the .m3u8 file. It works fine but we use track files as external files and do not want to embed it to m3u8 file. I think the problem occurs from this situation. I hope this case may help you to find out the problem and fix

**Comment by shinefour** [comment] 2017-07-24 11:37
Hey, thanks for getting back.
I'm not sure what you're referring to. The **.vtt** is in no way connected to or included in the **.m3u8** file.
The m3u8 by itself works fine (as shown in the example) and the vtt file works fine with an mp4.
Just in combination not.

**Comment by hazarartuner** [comment] 2017-07-24 11:50
@shinefour I'm sorry I said wrong. When I say your sample, I mean "videojs-contrib-hls's" own sample: http://videojs.github.io/videojs-contrib-hls/ :)

**Comment by shinefour** [comment] 2017-07-25 08:03
Ah, but that can't be the solution, right? I'm not generating that m3u8 file and adding html5 tracks is something the videojs clearly supports as seen in the other examples. sorry for insisting.

**Comment by hazarartuner** [comment] 2017-07-25 08:17
Yes I aggree with you. This can't be the solution. Actually I wished to notify one of the contributors in this repo :D Maybe it would help them for where they should look for :D Btw, english is not my mother language,  I'm so sorry If I make confusing sentences :D

**Comment by shinefour** [comment] 2017-07-25 15:29
No worries, I get what you're saying.
let's see if someone else can help. not sure how they review these things here. would really appreciate any help

**Comment by shinefour** [comment] 2017-07-25 20:00
can the "needs info" label be deleted as to not confuse people? I think all info has been provided, right?

**Comment by hazarartuner** [comment] 2017-07-26 08:59
Yes I agree.

**Comment by gesinger** [comment] 2017-07-26 20:54
Thanks for the info @shinefour and @hazarartuner . I see the issue. Another interesting note is that if you include `default` in the track, it will show the first caption in safari (overlayed by the error).

**Comment by shinefour** [comment] 2017-09-20 09:24
@gesinger 
Hey Garret, I wanted to check if you have an idea about solving this problem. is there anything that I can do to help?

**Comment by mjneil** [comment] 2017-09-20 16:24
Not really sure why this isn't working in safari, especially since I can get it to working locally with a different m3u8 and vtt source, but not with yours. However, I could get your sources working locally by disabling native text tracks `videojs.options.html5.nativeTextTracks = false`. Maybe give that a try and see if it fixes your issue?

**Comment by mjneil** [comment] 2017-09-20 16:33
you might need to move the videojs script tags into your `<head>` as well
Also, I was a bit misled with, "got it working with your sources", by moving the script tags to the top, I don't get the media error, but safari encounters an error when trying to request your vtt file (though it doesn't provide any error message or status code...), but if I download and host your vtt file locally it works. There may be an issue with how you are serving your vtt file as well

**Comment by hazarartuner** [comment] 2018-01-26 13:41
@gesinger @shinefour I wasn't looking for this issue for a long time, this week I had to check it again and found the problem for my situation. I think there is no bug, subtitles do not come because ios behaves strictly on cross origin errors and blocks text tracks. I noticed that in my app I recieve cors errors, after I fix it, subtitles begin to work :D Hope it'd be helpfull :)

**Comment by gesinger** [comment] 2018-03-13 21:56
Thanks for the update @hazarartuner . Closing for now. If anyone is still experiencing this issue with the latest version of videojs-contrib-hls, please let us know. Thank you.

**Closed by gesinger** 2018-03-13 21:56 UTC
Labels: confirmed
