### ISSUE TITLE
Segments fetching endless loop

### ISSUE THREAD

**Issue by norlin** [videojs/videojs-contrib-hls#478] opened 2015-12-16 12:24 UTC
Hello!
Bug is reproducable only with some streams.
Here is the example:
http://jsbin.com/judetevufa/1

1. open this example in Chrome
2. open devtools network pane
3. look at the requests

Screenshot: http://norlin.guru/st/hls-loop_1C218ED7.png

I'm not sure what's happening, but maybe it's a bug with decoding.

**Comment by codex-corp** [comment] 2015-12-18 15:33
@norlin 
i have the same problem , wired .

**Comment by outlawtorn** [comment] 2016-01-13 07:39
I have the same problem. The temporary fix is to set the preload to "none" and set controls to true.

**Comment by norlin** [comment] 2016-01-13 07:45
@outlawtorn Thanks, but it seems doesn't help for me...

**Comment by outlawtorn** [comment] 2016-01-13 08:33
hi @norlin in your jsbin i edited the video tag to 
<video id=example-video width=600 height=300 class="video-js vjs-default-skin" controls preload=none>
and it works.

**Comment by norlin** [comment] 2016-01-13 08:54
@outlawtorn Hmm, weird, for me it's still not working:
Screenshot: http://norlin.guru/st/hls_bug_preload_1C46480D.png

**Comment by outlawtorn** [comment] 2016-01-13 14:38
I think there is some problems in the encoded source file.
Try this source http://solutions.brightcove.com/jwhisenant/hls/apple/bipbop/bipbopall.m3u8.

**Comment by norlin** [comment] 2016-01-13 15:00
@outlawtorn I know it's happening only with some files. But it's a bug with decoder, I guess, not with files.

**Comment by huangyg11** [comment] 2016-02-25 05:18
![image](https://cloud.githubusercontent.com/assets/5545682/13310587/3f4926da-dbc2-11e5-9f02-36011121f978.png)

+1

**Comment by hyurtseven81** [comment] 2016-02-26 20:12
Same with this: https://cdn.blutv.com.tr/kdv/S6/HLS_VOD/92658_d24b/index.m3u8
also there is lip sync problem with this hls but on our old player http://quark.dogannet.tv/player, there is no problem

**Comment by hyurtseven81** [comment] 2016-03-23 21:24
Same with 2.0.1 version

**Comment by thenewguy** [comment] 2016-04-06 13:40
I've encountered this with a VOD master playlist on version v1.3.11

**Comment by thenewguy** [comment] 2016-04-06 15:36
It looks like updating to v2.0.1 fixes the issue on the stream giving me problems.  Couldn't update to v2.1.1 because the release doesn't include dist files and I couldn't get my vagrant box to build the code

**Comment by thenewguy** [comment] 2016-04-06 20:01
So upgrading to v2.0.1 did not fix the problem.  The problem was hidden because this version will play one particular variant playlist but none of the others and happened to select the variant that played when I was checking different streams

**Comment by thenewguy** [comment] 2016-04-13 17:24
I figured out the issue with the video that was giving me trouble.  After ensuring both the height and width were divisible by 2 and converting it to yuv420p the issue is gone.

**Comment by forbesjo** [comment] 2016-07-06 20:44
If anyone is still having this problem please comment and I'll reopen, this should be fixed.

**Closed by forbesjo** 2016-07-06 20:44 UTC
