### ISSUE TITLE
Primary - Backup failover issues

### ISSUE THREAD

**Issue by TV5Dev** [videojs/videojs-contrib-hls#753] opened 2016-06-22 08:34 UTC
## Description

Switching between primary and backup stalls playback.
http://jsbin.com/civobidata/edit?html,js,output
.HAR file (not captured on this testpage, but same behavior): https://drive.google.com/file/d/0B5Ua8dMrWZaldkVOVDM2N2FWaTg/view?usp=sharing 
video (not captured on this testpage, but same behavior): https://youtu.be/jGwq-ToGXVI 
## Steps to reproduce
1. Navigate to http://jsbin.com/civobidata/edit?html,js,output
2. Notice playback starts on backup stream.
3. After watching for some seconds, enable chrome throttling - "Regular 3G"
4. Playback switches to primary stream.
5. Playback freezes, until it switches back to the backup stream.

Could also use chrome network tab, update hostsfile to make the backup point to localhost, use "close idle sockets".
1. Primary and Backup encoders are running. 
2. Player starts playing on backup due to video-js-contrib selectPlaylist logic. (no custom code - default behavior) 
3. During playback, stop Backup encoder. 
4. There is no update for the child playlist for the Backup encoder, and Akamai responds with 404 error. 
5. Upon receiving '404' for the Backup child playlist, it requests for Primary child playlist and the player hangs. 
6. Player continues only after refreshing the page. When no child playlist segments have been downloaded yet. 
### Expected

Switch from Primary to Backup stream. Our encoders are in a 1+1 setup; not linked to each other.
All primary child playlist segments have different file names, although the content is in sync.
### Actual

Playback freezes when switching from primary to backup or from backup to primary.
### Error output

No errors
## Additional Information

Please include any additional information necessary here. Including the following:
### Sources

Livestream, happens at all times.
### videojs-contrib-hls

videojs-contrib-hls 3.1.0
#### videojs

video.js 5.10.4
#### browsers

Can only simulate it currently in Chrome, Firefox.
Was not able to simulate encoder failure on Edge or Safari.
#### Operating Systems

what platforms (operating systems and devices) are affected?
Windows tested only
### plugins

are any other videojs plugins being used on the page? If so, please list them with version below.
/
### Other JavaScript

are you using any other javascript libraries or frameworks on the page? if so please list them below.
/

**Comment by TV5Dev** [comment] 2016-06-28 06:19
I have just curled some of my playlist files.

The primary child playlist contains following:
#EXTM3U
#EXT-X-TARGETDURATION:9
#EXT-X-MEDIA-SEQUENCE:5594
#EXTINF:9,
While the backup child playlist contains following:
#EXTM3U
#EXT-X-TARGETDURATION:9
#EXT-X-MEDIA-SEQUENCE:72745
#EXTINF:9,

Could anyone confirm that for primary / backup failover this sequence number needs to be exactly the same, and that the .ts file names don't matter at all?

Thanks in advance.

**Comment by TV5Dev** [comment] 2016-07-08 03:07
https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#section-6.3.2
A client MUST NOT assume that segments with the same Media Sequence
Number in different Variant Streams or Renditions have the same
position in the presentation; Playlists MAY have independent Media
Sequence Numbers.

So looking into another reason on why this is happening.

**Comment by TV5Dev** [comment] 2016-07-08 09:53
Looks like videojs-contrib-hls is using the sequence numbers to calculate the position.

http://pastebin.com/xYWvZdm7 @ line 550 you can see what happens when it switches from primary to backup.

**Comment by RyanEdwardHall** [comment] 2016-07-25 18:06
I've encountered this problem too. If the media sequence number of the backup stream is behind master, the player will sit in a buffering state until it catches up. Have you found a good resolution?

**Comment by TV5Dev** [comment] 2017-02-02 03:18
Well... The root cause was not the Media Sequence Numbers, but rather PTS/DTS timestamps in individual .ts packets not being in Sync. Using a MPEG-2 TS packet analyser, you can download the matching segments between primary and backup (same video), and open both in the analyser. Then you may see the PTS/DTS timestamps. This number should be very close to each other, if not identical. Now if this is not the case, it's only normal that the player would keep searching for next presentation timestamp in other packets, which will never be found, causing it to hang or loop forever.

**Comment by bradleyfalzon** [comment] 2017-02-02 05:19
If a playlist switches, the player should also know that the timestamps will not match between segments, it should treat the new playlist as if it had a discontinuity flag. 

I'd say the issue is not that the two backends had different timestamps, but the player, when switching should've been aware this would happen and do whatever it does when it comes across a EXT-X-DISCONTINUITY flag.

**Comment by TV5Dev** [comment] 2017-02-02 05:35
Reading through the HLS spec : https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#section-6.2.4

- Each Variant Stream MUST present the same content. (quite impossible when you have two independent systems generating the same stream)
- Matching content in Variant Streams MUST have matching timestamps. This allows clients to synchronize the media.

You can download the ffmpeg package, which includes ffprobe, which allows you to analyse the segment PTS/DTS values. "ffprobe -show_entries packet=codec_type,stream_index,pts,dts inputfile> output"
Also having tried various famous players, all have the same problem, they get stuck when trying to switch to a failover playlist.
For example one can see the primary PTS would be 7214757856 and the backup PTS would be 4747165408.
However for working failover streams we can see the PTS/DTS values are aligned quite closely.

Filenames or media sequence number do not matter for failover to work, unless the players have implemented the HLS spec wrongly.

**Comment by bradleyfalzon** [comment] 2017-02-02 05:46
`Matching content in Variant Streams MUST have matching timestamps. This allows clients to synchronize the media.` Yes, that does make my statement incorrect, thanks for clarifying.

**Comment by topherlandry** [comment] 2017-02-02 23:12
@TV5Dev Did you solve this problem for your system then? It sounds like it would be quite the feat to ensure that the packets were in sync with PTS, since analyzing during transcode to figure out where your PTS would begin could be off, since that is a moving target.

I suppose that's not terrible if you are able to estimate since you've found that closely aligned values are not at fault.

**Comment by TV5Dev** [comment] 2017-02-27 03:57
The problem we face is the primary and backup are from 100% independent sources. Haven't found a solution for our case other than using a device which takes two signals and outputs it into one. This one signal would then be encoded into a primary and backup stream. (from the same source) However having this device would beat the purpose of a failover since it's not redundant...

**Comment by topherlandry** [comment] 2017-02-28 19:29
It should be fine, because "primary / backup" are really just terms we use for simplification. Should be good for all variant streams.

**Comment by gesinger** [comment] 2017-04-05 00:03
Thanks @TV5Dev for all of the information. As mentioned, the HLS spec includes "Matching content in Variant Streams MUST have matching timestamps. This allows clients to synchronize the media." Without the match, the player can't make reasonable determinations about the content. Closing this issue for now, but if anyone finds any other solution to the problem of out-of-sync primary backup failover, we're happy to hear the suggestions. Thanks again.

**Closed by gesinger** 2017-04-05 00:03 UTC
