### ISSUE TITLE
Problem Encountered with the Current HLS Playlist

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/videojs-contrib-hls#1161] opened 2017-06-13 09:14 UTC
Hello,
I'm using videojs-contrib-hls (5.4.1) and I'm getting this warning.

> VIDEOJS: WARN: "Problem encountered with the current HLS playlist. HLS request errored at URL: http://5flix.cdn.octivid.com/vod/_definst_/smil:2017-05-22/vidtXQaCOL9U3.smil/media_b201716_14.ts Switching to another playlist."

Any idea why?

Thanks.

**Comment by gesinger** [comment] 2017-06-13 14:16
Hey @maryam-abdullah , it looks like the http request for that TS segment had an error (could be a timeout, lost connection, server had an error, etc.). Would you be able to check your network tab in developer tools to see what the response is? Thanks.

**Comment by maryam-abdullah** [comment] 2017-06-14 06:38
Well, I'm no longer experiencing this error. 
Once I do, I will probably post the response in the network tab.

**Comment by gesinger** [comment] 2017-06-14 15:01
I'm not sure why they're not in the network tab. Did you get the network tab screenshot around the same time as those errors occurred?

**Comment by gesinger** [comment] 2017-06-14 15:02
And which browser are you using?

**Comment by maryam-abdullah** [comment] 2017-06-14 15:05
I took the screenshot after the warning occured.
And I'm using Chrome.

**Comment by gesinger** [comment] 2017-06-14 15:09
Is there anything else in the console log? And would you be able to link your playlist?

**Comment by maryam-abdullah** [comment] 2017-06-14 15:13
There's nothing else. And I'm actually suspecting that it's cause of the Internet connection. Cause it doesn't happen all the time.

**Comment by gesinger** [comment] 2017-06-15 16:36
It's possible it's from the internet connection, though I'd still expect to see something in the network tab or in the console. It's hard to diagnose without being able to reproduce it though. Any chance you'd be able to find a way to reproduce it (if it is internet connection related, maybe using chrome's network tools)?

**Comment by maryam-abdullah** [comment] 2017-06-15 18:49
Is it possible to reproduce it? If so, please tell me how.
Once it occurs again, I will check the network tab to see the response.

**Comment by gesinger** [comment] 2017-06-20 22:35
@maryam-abdullah , you can try using Chrome's network tools (specifically their throttler) to slow down and disable your internet connection.

**Comment by maryam-abdullah** [comment] 2017-06-21 07:14
I tried what you told me, but the warning message no longer appears.

**Comment by gesinger** [comment] 2017-06-21 14:24
That sounds like good news! In that case, I'm going to close this issue. If you see it happening again, try to create a reproducible test case for it and open a new issue. Thank you.

**Closed by gesinger** 2017-06-21 14:24 UTC
Labels: needs:info

**Comment by mohsinworld** [comment] 2018-08-01 23:12
I face the same thing. The link is work on VLC media player but not work in the web player. what is the solution here? This is the link http://ipme.oncast.me:1935/forchannels/boishakhitv-org-forchanels.stream/playlist.m3u8
