### ISSUE TITLE
HLS Audio-only streams do not work on 5.5.1+

### ISSUE THREAD

**Issue by teveo** [videojs/videojs-contrib-hls#1186] opened 2017-07-03 17:46 UTC
HLS audio-only streams don't play on version >= 5.5.1. v5.5.0 is not affected by this issue. TS Segments are being downloaded according to Google Chrome's developer tools, but it does not play

**Comment by mjneil** [comment] 2017-07-03 17:49
Sounds like this is a duplicate of #1179 ?

**Comment by h94** [comment] 2017-07-07 02:57
Video.js: ^6.2.0
videojs-contrib-hls: ^5.7.0
http://jsbin.com/lejevodecu/edit?html,output

**Comment by samueleastdev** [comment] 2017-07-07 11:09
Yes, this is exactly the same problem as @mjneil mention tested up to 5.8.0

**Comment by h94** [comment] 2017-07-10 03:25
In webpack inside?

**Comment by mjneil** [comment] 2017-07-12 21:52
This has been fixed by #1195 please update to videojs-contrib-hls v5.8.1 to start using the changes. If you still experience issues please open a new issue.

**Closed by mjneil** 2017-07-12 21:52 UTC
Labels: bug, confirmed, in progress
