### ISSUE TITLE
Switching of Audio Tracks sometimes leads to exception/crash

### ISSUE THREAD

**Issue by architsinha** [videojs/videojs-contrib-hls#950] opened 2017-01-08 09:14 UTC
## Description
Briefly describe the issue.
Switching the audio Tracks sometimes causes either of the two following exceptions and consequent freeze/crash.
a. _VIDEOJS: ERROR: (CODE:-3 undefined)  e {code: -3, type: "APPEND_BUFFER_ERR", message: ""}_
b. _VIDEOJS: ERROR: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer', 'appendStream', or 'remove' operation._

I suppose the reason is that when the audio track is swtiched, the sourceBuffer is flushed by a _remove()_ call. So whenever _appendBuffer()_ gets called before remove() is completed or vice versa, we get the first or second exception respectively. I confirmed this by printing the _updating_ flag of the sourcebuffer, before remove() and appendBuffer(), whenever the issue occurred, the flag was true.

So my questions are:
1. Is this issue being observed by anyone else or am I missing something or doing something incorrect? I couldn't find it in any of the existing issues?
2. Any suggestions on fixing the issue. One way probably could be to check the updating flag and if true set a timeout and try again.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

I am using the link mentioned below for testing, though I guess any stream with multiple audio tracks should suffice:
http://demo.unified-streaming.com/video/elephantsdream/elephantsdream-multiple-audio.ism/.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the link mentioned above( any other stream with multiple audio track should also suffice I think).
2. Keep switching the audio Tracks after every few seconds. 
3.  After some attempts, you will see the video freezing  and one of the two exceptions mentioned in the beginning can be seen in the console

Please note that the issue does not happen on every switch, it needs multiple switches to get the error.

### Expected
Stream should continue to play properly after switching audio Track

### Error output
Either one of the two:
a. _VIDEOJS: ERROR: (CODE:-3 undefined)  e {code: -3, type: "APPEND_BUFFER_ERR", message: ""}_
b. _VIDEOJS: ERROR: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer', 'appendStream', or 'remove' operation._

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 4.0.2

### videojs version
what version of videojs does this occur with?
video.js 5.11.9

### Browsers
what browsers are affected? please include browser and version for each
I have tested with Chrome version 55.0.2883.87 m

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Windows 7

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
No

**Comment by gesinger** [comment] 2017-02-17 23:29
Thanks for reporting @architsinha . Confirmed with latest version (v5.3.0) and the provided source.

**Comment by mjneil** [comment] 2017-06-14 21:54
We've made some improvements to the `SourceUpdater` and `VirtualSourceBuffer` that should fix these issues. Can you try out the latest version (v5.5.3) and see if it resolves the issues for you?

**Comment by gesinger** [comment] 2018-03-15 17:25
Looks like this has been fixed. Closing. If you are still experiencing issues with the latest version of videojs-contrib-hls, please let us know. Thank you.

**Closed by gesinger** 2018-03-15 17:25 UTC
Labels: bug, confirmed
