### ISSUE TITLE
Playlist switch causing playback pause

### ISSUE THREAD

**Issue by powrsurg** [videojs/videojs-contrib-hls#843] opened 2016-09-12 21:54 UTC
## Description

Briefly describe the issue.

When a playlist is switched (e.g. change in bandwidth) the player and the player reaches a segment it has downloaded for the previous playlist, but not for the current one, it will get stuck.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.

We have a video (unfortunately not publicly available) where when we first load the video it will download the first three segments (segment 00.ts - 12 seconds, segment 01.ts - 12 seconds, and segment 02.ts - 6 seconds) in length. I quickly use Chrome's dev tool to limit my network access to a Regular 3G connection. This results in it downloading a lower quality playlist and the next segment it should need (segment 03.ts). Unfortunately the player stops at the 24 second mark, and will no longer download any new segments. If you scrub forward a little it will resume playing.
### Expected

Please describe what you expected to happen that did not happen in the description.

We expect the player to play the segment 02.ts and reach 30 seconds, and then switch to the lower quality version for 03.ts.
### videojs-contrib-hls version

what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.5.2
### videojs version

what version of videojs does this occur with?
video.js 5.10.4
### Browsers

what browsers are affected? please include browser and version for each
- Chrome, Firefox
### Platforms

what platforms are affected? please include operating system and version or device and version for each
- Windows 10

**Comment by powrsurg** [comment] 2016-09-13 15:27
I was allowed to take another video, so I have posted an example codepen:

http://codepen.io/powrsurg/full/jrWzLv/

If you let the video play for a few seconds and then use Chrome's Dev Tools to throttle the speed to, say, Regular 3G, the video will end up pausing during playback.

**Comment by forbesjo** [comment] 2016-09-29 19:34
We may have a fix for this, stay tuned :tv:

**Comment by nhollander** [comment] 2016-10-06 04:12
Hi we are experiencing the same issue for live. Any update on the fix @forbesjo ? 

This looks like there is an issue with packager at the encoder as well as player itself. The reason being why the issue is replicable in all players as well as in safari is due to packager not updating the chunk lists with current ts set causing the player running out of buffer.
 
We are able to replicate the issue and seeing player is requesting only chuncklists repeatedly and not playing ts segments.

Capturing HTTP request and response confirms the following behavior:
 
1. After the chuncklist master_270p.m3u8 which has 00385.ts, the next request for the same ts segment is successful

 

2.    ![image](https://cloud.githubusercontent.com/assets/22651257/19140185/dae0073c-8b47-11e6-81c5-8342f9f85a94.png)

 
 
After that, for more than 1 minute, the chuncklist is not updated with current ts segments causing only to request chuncklist and buffering out player.

![image](https://cloud.githubusercontent.com/assets/22651257/19140201/063f4f5a-8b48-11e6-825c-9c704947c110.png)

![image](https://cloud.githubusercontent.com/assets/22651257/19140214/27de6c0e-8b48-11e6-9c67-2f00229e6e1f.png)

We also see the player also requesting same ts segments multiple times as well as in random orders.
 
Sample log lines for the client requested ts segments- time sorted:
 
# time #object_size #content-byte_served #status code #ARL
2016/09/27-22:01:45+0000 1663236 1663236 200 hls/live/261224/mrtest/master_360p_00415.ts
2016/09/27-22:01:45+0000 1663236 1663236 200 hls/live/261224/mrtest/master_360p_00415.ts
2016/09/27-22:01:45+0000 1663236 1663236 200 hls/live/261224/mrtest/master_360p_00415.ts
2016/09/27-22:01:45+0000 1663236 1663236 200 hls/live/261224/mrtest/master_360p_00415.ts
2016/09/27-22:01:46+0000 1663236 1663236 200 hls/live/261224/mrtest/master_360p_00415.ts
2016/09/27-22:01:50+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:51+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts  -à random order
2016/09/27-22:01:51+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:51+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:51+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:51+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:51+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:52+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:52+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:52+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:52+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:52+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:53+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:53+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:53+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:53+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:53+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:54+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:54+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:54+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:54+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:54+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:55+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:55+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:55+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:55+0000 667024 667024 200 hls/live/261224/mrtest/master_270p_00413.ts
2016/09/27-22:01:56+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:56+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:56+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts
2016/09/27-22:01:57+0000 671912 671912 200 hls/live/261224/mrtest/master_270p_00414.ts  -> multiple requests
 
As you also will see that there is one more weird behavior that no ts requests made by the player for more than 1minute, though the ts segments are advertised. (After master_720p_00661.ts no requests for ts but chunk list showing till master_720p_006618ts).
 
![image](https://cloud.githubusercontent.com/assets/22651257/19140277/c42d656a-8b48-11e6-8c7d-554147edf50a.png)

The same behavior cannot be replicated in IOS native player (safari). This shows that the issue is more likely with the HTML5 player implementation.

**Comment by nhollander** [comment] 2016-10-06 17:25
Here is a live Stream to test with in our player: 

http://devmobilerider.com/users/julio/test_player_20160928.html

**Comment by Agnostic** [comment] 2016-11-10 19:34
I have the same issue, any updates on this @forbesjo?

**Comment by powrsurg** [comment] 2016-11-14 16:01
I just updated to the latest versions of VideoJS and the HLS plugin and it seems to be working for me. The player does get to spots where it may pause as it buffers, but it continues to play once it has the necessary segments.

**Comment by Agnostic** [comment] 2016-11-14 18:18
The issue is that the player tries to get always the best resolution available, even if it fails at the first time, if you look at the network log it will show something like this:

Downloading chunk (512) ... (exceeds timeout)
Downloading chunk (256) (Loaded successful) Video starts...
Downloading chunk (512) ... (exceeds timeout) - Video pauses...
Downloading chunk (256) (Loaded successful) Playing...
Downloading chunk (512) ... (exceeds timeout) Video pauses again...

So I think the video should be playing smoothly based on the bandwidth instead of pausing every time it tries to download the biggest chunk.

**Comment by gesinger** [comment] 2017-03-20 22:27
Sorry this ticket has gone a long time without much attention.

We've made a lot of changes to videojs-contrib-hls in the meantime, and it looks like the original issue may have been resolved.

For anyone still having trouble with the issue, please give the latest version of videojs-contrib-hls (as of this comment, v5.3.3) a shot. If it's still a problem, please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Closed by gesinger** 2017-03-20 22:27 UTC
