### ISSUE TITLE
How to encrypt m3u8 video, request key to encrypt the encrypted string, and how to decrypt the player

### ISSUE THREAD

**Issue by huanghanzhilian** [videojs/videojs-contrib-hls#1392] opened 2018-03-28 07:25 UTC
How to encrypt m3u8 video, request key to encrypt the encrypted string, and how to decrypt the player

**Comment by gesinger** [comment] 2018-03-28 14:14
Duplicate of https://github.com/videojs/videojs-contrib-hls/issues/1393

**Closed by gesinger** 2018-03-28 14:14 UTC
