### ISSUE TITLE
hls adaptative problem

### ISSUE THREAD

**Issue by arielin82** [videojs/videojs-contrib-hls#800] opened 2016-07-28 21:12 UTC
## Description

Hi,
i have problems with the video resolution, the player always select the lower resolution, I have 3 resolution in the master playlist

But despite i really good bandwith hls player starts loading the 720p .ts files but then it changes to the 240p playlist.

But if i use the "hlsplayer.net" or "flashls" they always get the maximum resolutiona automatically ( 720p) videos so i think the problem is with the videojs player.

Another thing to mention is that if it is working in 720p and I change the bandwith connection with the google crhomre tool to a lower bandwith, the players download to 240p but if i change the bandwith to high again the player doesn't change the playlist that its using to the 720p. it never increase the resolution.
## Sources

Here is my m3u8
https://s3.amazonaws.com/blink-webinars-video/d895e7a4-0e61-4de0-926e-62045d501ca6/webinar-replay-new.m3u8

I think the is a problem with the bandwith calculations and it doesn't reload or change to the correct playlist.
There is any way to make the player select the playlist programatically? 
### videojs-contrib-hls version

videojs-contrib-hls 3.1.0
### videojs version

what version of videojs does this occur with?
video.js 5.10.5
### Browsers

Chrome Version 52.0.2743.82 (64-bit)
firefox 47.0

**Comment by forbesjo** [comment] 2016-09-01 19:31
I'm seeing it select the 720p playlist, is this still an issue for you?

**Comment by gesinger** [comment] 2017-01-20 18:36
Closing since we can't reproduce. Please re-open if this is still an issue on the latest player, and please provide a reduced test case using [this template](http://jsbin.com/liwecukasi/edit?html,output) if you can. Thank you.

**Closed by gesinger** 2017-01-20 18:36 UTC
Labels: needsinfo
