### ISSUE TITLE
error of videojs-contrib-hls about webworkify

### ISSUE THREAD

**Issue by cucygh** [videojs/videojs-contrib-hls#1153] opened 2017-06-06 08:47 UTC
## Description
when use videojs-contrib-hls by npm,it can't work,the error occur in webworkify.
we have a [starter template](http://jsbin.com/sumajabano/edit?html,js,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.
I read the source of videojs-contrib-hls,when it use webworkify module,in this module it use arguments,
<code>
var bundleFn = arguments[3];
var sources = arguments[4];
var cache = arguments[5];
</code>
but when pack with webpack and gulp ,bundleFn 、sources、cache is undefined. so the error occurs.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. follow  [this page](http://jsbin.com/sumajabano/edit?html,js,output)
2. pack with webpack and gulp
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
<img src="http://i1.piimg.com/596059/bff1cb2697efc653.png"/>
## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js 5.19.2

### Browsers
what browsers are affected? please include browser and version for each
*all

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*all

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* videojs-contrib-hls

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*none

**Comment by gkatsev** [comment] 2017-06-06 15:28
Hey, this sounds like a dupe of #600. Unfortunately, right now you have to include `webworkify-webpack-dropin` because the module we use is browserify specific. You can see an example config here: https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-258400412
Hope that helps.

**Closed by gkatsev** 2017-06-06 15:28 UTC
