### ISSUE TITLE
Not working on IE11-Win7 VM

### ISSUE THREAD

**Issue by swordsreversed** [videojs/videojs-contrib-hls#825] opened 2016-08-19 02:49 UTC
## Description
Using the modern.ie VM for IE11 on Windows 7 the error "No compatible source" appears.
This is using the reduced test case.

## Sources
[http://jsbin.com/liwecukasi/edit?html,output](http://jsbin.com/liwecukasi/edit?html,output)

## Steps to reproduce

1. Run IE11-Win7 from [https://github.com/markhuber/modern-ie-vagrant](https://github.com/markhuber/modern-ie-vagrant)
2. Load reduced test case

![screen shot 2016-08-19 at 12 41 12](https://cloud.githubusercontent.com/assets/2155844/17797323/56c2165e-660b-11e6-9020-07aefb26604f.png)

### Expected
The text case to play.

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. [object Object]

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
3.0.2

### videojs version
video.js 5.10.2

### Browsers
IE11

### Platforms
Windows 7 (VM)

**Comment by forbesjo** [comment] 2016-08-19 02:56
Does your VM have Flash installed?

**Comment by swordsreversed** [comment] 2016-08-19 03:20
I didn't so I installed Flash 22.0, restarted and tried in a private browsing tab (no caching) and still couldn't get it to play. Same error in console. Do you have different result?

**Comment by BrandonOCasey** [comment] 2016-08-19 14:12
Did you change the `techOrder` to force flash playback on ie11? Its currently a know issue that some implementations of IE11 in the wild have issues that they should not. We think it was due to codecs installed on the machine.

Here is a better example of forcing flash (just in case):

```
var player = videojs('my-video-id', {techOrder: ['flash']);
```

**Comment by swordsreversed** [comment] 2016-08-19 14:48
So I just tried 

```
var player = videojs('my_video_1', {techOrder: ['flash']});
```

and still no luck. Perhaps its also a jsbin issue as the [main example](http://videojs.github.io/videojs-contrib-hls/) works. Strange.

**Comment by forbesjo** [comment] 2016-09-01 19:55
Closing since this only seems to be a problem in jsbin and not in a real page

**Closed by forbesjo** 2016-09-01 19:55 UTC

**Comment by samueleastdev** [comment] 2017-03-10 12:55
I was also getting this error on IE 11 

~~~
No compatible source
~~~

But after installing flash then everything worked fine, can we alert the user that not having flash installed is the cause of the issue?

How would you hook into a specific error message for IE using the video js framework? and present the user with a clearer message informing them to download flash ill have a go at setting it up.

Thanks
