### ISSUE TITLE
Video freezes, randomly

### ISSUE THREAD

**Issue by achru** [videojs/videojs-contrib-hls#740] opened 2016-06-10 12:59 UTC
Randomly, video freezes, in some points
sometimes it happens, sometimes it doesn't - after freeze if i move to the next second it works again,
on safari working without any issue,

videojs 5.10.2
videojs-contrib-hls 3.10

in order to reproduce, 
paste that code somewhere
`
<div class="noddus-player" data-url="http://noddus.com/widget_campaign?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwbGFjZW1lbnRfaWQiOjgwLCJjYW1wYWlnbl9pZCI6ODh9.xnUYavbwF2OyoQdjqUlVM_g-yGJd4z9rlQs1yMshbIU"></div> <script type="text/javascript" src="http://noddus.com/javascripts/loader.js"></script>
`

it does not fail all the times, but some of them, any idea why ?

**Comment by leighfarrell** [comment] 2016-06-15 17:35
+1

I'm encountering the same issue. Others have reported video playback freezing, however I haven't been able to recreate. It's primarily happening in IE, though we have a few reports of it occurring in Chrome.

**Comment by powrsurg** [comment] 2016-06-15 18:16
We were running 1.3.11 with videojs 5.10.4 and one of our developers was experiencing that in Chrome, usually on videos that he has fullscreened. I just updated to 3.1.0 and am getting it pretty consistently with new videos. If you restart it works fine.

One thing I'm noticing is it seems to skip segments. For instance, in a recent occurrence it downloaded chunk 01.ts and then 03.ts and I had to click the video on the progress bar and to force it to get 02.ts.

**Comment by powrsurg** [comment] 2016-06-17 16:40
I have found that the fixes from the live-stream-fixes branch seem to correct the issue for me.

**Comment by achru** [comment] 2016-06-20 15:10
tried that branch, but same thing happens

**Comment by jpfranco** [comment] 2016-07-07 00:08
We've been experiencing the same issue lately. I've been able to reproduce it consistently using this source:
[Source](https://authproxy-s1.gbstage.com/s3-m3u8/organization-notverifiedacc/video-BkNeWSO8/video-hls3.m3u8?Signature=KOqzpIWe3McfaCY7KkCTkInW3Gf10deMuurnG437V64rbCFeLwFBaWzwm6Tt~jjip2h8VyRoee52mW2YtxFUstGFOCRq89gmAwaZRWXWfFZY92nxV-LeOg1KK~UhboRaTDnfh7VVxfDBPEGVREVSmhHS~eV935DGDbdgDxpsvpgjkljXlk~gOcRL2Eda-Wzy3f1AhhAGxk3XquDhSpf3m1we3LmoeIO~G2yCe66QLwTmNGxifWLfG7jPlSehxVHB7k-55-iObaXGPIHZFEEP-WWWBJIE1qV5rGkU7zNj-5U8ev~jFtU3DU4aN62uGGSzmlhoeoDgb31i~w16jaxe0A__&Key-Pair-Id=APKAJ5JH3L2ZNI5QDHEQ&Expires=2147483647)

The issue occurs randomly and always at a different position, but it's very easy to reproduce if you just let the video play in the background and come back later. Once the video freezes no more chunks are downloaded until you seek past the frozen point. If you seek to a previous time though, the video will freeze again when reaching the time at which the problem occurred. 

This was seen on Chrome (latest) using VideoJS 5.10.4 and videojs-contrib-hls 3.1.0.

**Comment by Rellim7** [comment] 2017-02-14 00:31
I have encountered what i think is a similar issue to this on a later release.

windows/chrome
videojs 5.16
videojs-contrib-hls 4.1.1

A video will consistently freeze at 1:17 with this combo.   Here is a jsbin of the video that will do it.

http://jsbin.com/miyunoleqa/edit?html,console,output

This might be a separate issue though.

**Comment by laurent-dazzl** [comment] 2017-02-23 16:13
Same (?) issue with live casts using Evostream Media Server solution.
video.js version 5.16.0, videojs-contrib-hls 5.2.1
HLS play fine with Safari on MacOS, Safari on iOS, firefox on iOS, Chrome on Android,
but freeze on chrome and firefox on MacOS.

Chrome gives more logs :
a first error 
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.
```
then a repeated error (maybe each time the playlist is reloaded) : 
```
Uncaught DOMException: Failed to set the 'duration' property on 'MediaSource': The MediaSource's readyState is not 'open'.
    at t.value (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:4:17490)
    at t (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:1:9271)
    at https://live.dazzl.tv/js/videojs-contrib-hls.min.js:1:9452
    at v.<anonymous> (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:1:9456)
    at value (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:2:23231)
    at f (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:1:26122)
    at https://live.dazzl.tv/js/videojs-contrib-hls.min.js:1:27894
    at Object.callback (https://live.dazzl.tv/js/videojs-contrib-hls.min.js:2:29268)
    at cbOnce (https://live.dazzl.tv/js/video.js:26494:21)
    at loadFunc (https://live.dazzl.tv/js/video.js:26570:16)
```

Firefox gives no logs, continue to get the playlist file but stop getting video segments

**Comment by gesinger** [comment] 2017-04-07 21:34
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, including around skipping and filling gaps, as well as around requesting segments in order to prevent browsers from creating gaps.

In addition, it looks like a few different problems were encountered.

@laurent-dazzl MEDIA_ERR_DECODE usually indicates a problem or unsupported feature of the stream itself, but is most likely a different issue from the gaps.

@Rellim7 , I gave your stream a shot with the latest version (as of this comment, v5.4.0), and it seemed to play through on Mac/Chrome. Would you be able to give it another shot, and if it doesn't work, let us know what version of Chrome you are using?

Thanks to all who reported. If you have a chance, please give the latest version of videojs-contrib-hls a shot (as of this comment, v5.4.0). And if you're still seeing issues, let us know the source you are using and what browser/OS. Thanks.

**Comment by asharptlm** [comment] 2017-04-10 10:54
I wouldn't say "randomly" but I am having a somewhat similar issue. Using videojs-contrib-hls with "overrideNative" on, and after a small fix (see below) I get the same MEDIA_ERR_DECODE. 

I have written my own monitoring Component in videojs for both the segment being streamed/downloaded, and the segment being played. At the point at which it tries to playback a segment from a different playlist, is when the error occurs. ie, it has acquired segments of a better quality, but crashes when it tries to play those segments.

For some further detail:

Platform: 2011 MacBook pro running macOS Sierra (10.12), error is on Safari Version 10.0 (12602.1.50.0.10). I am using videojs-contrib-hls version 5.4.0 with Video.js 6.0.0-RC.6

It DOES work however on desktop Chrome (which does not need overrideNative) and mobile Chrome (which does need overrideNative). The stream I am using (internal only, unfortunately) also plays fine in native Safari HLS support but of course I can neither see nor control what it is doing with the playlist.

I am also enabling cueTags in order to utilise the cuechange event to see when the playlist changes. With this enabled, for Safari to even start playing video at all (a TypeError occurs otherwise), I had to comment out this line in MasterPlaylistController:

this.cueTagsTrack_.inBandMetadataTrackDispatchType = '';

HOWEVER I have just tested without cues at all, and put that line back in, and I still get the Decode error, so I am certain it is unrelated. There are otherwise zero customisations to videojs and -contrib-hls libraries themselves.

**Comment by gesinger** [comment] 2017-04-10 20:38
Hey @asharptlm , thanks for all of the details. With `overrideNative`, we have some known issues around its use with Safari: https://github.com/videojs/videojs-contrib-hls/issues/1005 . The information you posted will be helpful in that ticket in helping to track down the root causes of the issues people are seeing.

**Comment by asharptlm** [comment] 2017-04-13 11:15
Thank you for response, @gesinger . I've also since discovered that on iOS (Chrome and Safari on iOS 9.3.5 for iPad, and Safari on iOS 10.xx tested so far) that overrideNative is having no effect - indeed no hls tech is loaded at all into videojs in such cases. Of course, I can use the native hls implementation just fine, but the additional insight into activity with your contrib package is very useful.

I didn't find any specific instructions for making the hls contrib package work on iOS, nor have I found anyone else reporting this as an issue - so forgive me if I've missed anything. I also apologise if this is not the best place to post the issue; I can make a separate report, but I figured all things related to overrideNative are really best in one place?

**Comment by gesinger** [comment] 2017-04-14 17:43
Thanks again for the info @asharptlm . Those problems look to be centered around overrideNative on Safari (both mobile and desktop). It would be helpful to add that info to https://github.com/videojs/videojs-contrib-hls/issues/1005 , and we can address them there.

For this ticket, it looks like there were a few different errors, though they were from a while ago.

Closing this ticket for now. Thanks to all who reported. If anyone is still seeing issues with the latest version of videojs-contrib-hls a shot (as of this comment, v5.4.1), please re-open this ticket or create a new issue with a reduced test case/example source, and let us know the source and what browser/OS you are using. Thanks.

**Closed by gesinger** 2017-04-14 17:43 UTC
Labels: needs:info
