### ISSUE TITLE
The duration of video change after seeking

### ISSUE THREAD

**Issue by cagen** [videojs/videojs-contrib-hls#480] opened 2015-12-17 04:12 UTC
I force the video.js to play HLS in flash mode, and sometimes after seeking, the duration of video will change dramatically. And the video seekable time range also changed, which means some segments of the video could not be fetch any more. And this may not happen every time, about 2/5 - 3/5 of my test will go wrong.

My environment and setup:
Mac OSX 10.11.1
Chrome  47.0.2526.80 (64-bit)
Adobe flash 20.0.0.228
video.js: 5.4.5
videojs-contrib-js: 1.3.1 (I also used v1.2.4, v1.3.0 before, and they have the same issue too)

This is a [simple test](https://plnkr.co/edit/cM0mlUY44hJUbaiRUff5?p=preview)
Both of them will go wrong occasionally. (Seeking a relatively short time forward may reproduce the issue more easily, especially when seeking into the cached time range. And the second video source is more easy to reproduce than the first one in my cases)

This is one of the simple test result: (using the second video source, default video duration is about 67 seconds)

> 67.833333
> 67.767333
> 67.771333
> 67.78733299999999
> 67.767333
> 55.915675467889905
> 49.645987376146785
> 51.689004904890155
> 36.68400490489016
> 25.616247531498907
> 44.41180116701764

I took more deep debug, and find that some of segments end is incorrect after `videojs.HlsHandler.prototype.updateEndHandler_` is executed.
I add some logs in `updateEndHandler_`:

``` javascript
if (timelineUpdate && segment) {
    console.log(segment.uri);
    console.log('pendingSegment_ bufferLength: ' + segmentInfo.buffered.length);
    console.log('pendingSegment_ bufferEnd: ' + segmentInfo.buffered.end(0));

    console.log('flash tech bufferLength: ' + this.tech_.buffered().length);
    console.log('flash tech bufferEnd: ' + this.tech_.buffered().end(0));

    console.log('segment end: ' + timelineUpdate);
    segment.end = timelineUpdate;
]}
```

And here is the result:
 (My local test, different video source, the correct duration is about 748 seconds, `high720p92.ts` is the last piece of the segment, average duration of segment is 8 seconds. Some of the irrelevant uncaught error has been filter out)

> high720p0.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 0
> flash tech bufferLength: 1
> flash tech bufferEnd: 10.634
> segment end: 10.634
> duration change: 748.154
> 
> high720p1.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 10.634
> flash tech bufferLength: 1
> flash tech bufferEnd: 17.786
> segment end: 17.786
> duration change: 748.146
> 
> high720p2.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 17.785999999999998
> flash tech bufferLength: 1
> flash tech bufferEnd: 25.796999999999997
> segment end: 25.796999999999997
> duration change: 748.157
> 
> high720p3.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 25.797
> flash tech bufferLength: 1
> flash tech bufferEnd: 33.785000000000004
> segment end: 33.785
> duration change: 748.145
> 
> high720p4.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 33.785
> flash tech bufferLength: 1
> flash tech bufferEnd: 41.795
> segment end: 41.795
> duration change: 748.155
> 
> high720p5.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 41.795
> flash tech bufferLength: 1
> flash tech bufferEnd: 50.805
> segment end: 50.805
> duration change: 748.165
> 
> high720p6.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 50.805
> flash tech bufferLength: 1
> flash tech bufferEnd: 58.791999999999994
> segment end: 58.792
> duration change: 748.152
> 
> high720p49.ts
> pendingSegment_ bufferLength: 0
> 
> high720p50.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 406.0647009646303
> flash tech bufferLength: 1
> flash tech bufferEnd: 414.0757009646303
> segment end: 414.0757009646303
> duration change: 748.1957009646303
> 
> // FLASH BUFFER END AND SEGMENT END ARE INCORRECT HERE!
> high720p51.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 414.07570096463024
> flash tech bufferLength: 1
> flash tech bufferEnd: 395.72670096463025
> segment end: 395.72670096463025
> duration change: 721.8467009646303
> 
> high720p32.ts
> pendingSegment_ bufferLength: 0
> 
> high720p33.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 265.401700494205
> flash tech bufferLength: 1
> flash tech bufferEnd: 273.388700494205
> segment end: 273.388700494205
> 
> high720p34.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 273.38870049420495
> flash tech bufferLength: 1
> flash tech bufferEnd: 281.399700494205
> segment end: 281.399700494205
> 
> high720p35.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 281.399700494205
> flash tech bufferLength: 1
> flash tech bufferEnd: 289.387700494205
> segment end: 289.387700494205
> 
> high720p36.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 289.387700494205
> flash tech bufferLength: 1
> flash tech bufferEnd: 297.39870049420495
> segment end: 297.39870049420495
> 
> high720p37.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 297.398700494205
> flash tech bufferLength: 1
> flash tech bufferEnd: 305.38570049420497
> segment end: 305.38570049420497
> 
> high720p39.ts
> pendingSegment_ bufferLength: 0
> 
> high720p20.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 162.37085728021836
> flash tech bufferLength: 1
> flash tech bufferEnd: 154.34985728021837
> segment end: 154.34985728021837
> 
> high720p40.ts
> pendingSegment_ bufferLength: 0
> 
> high720p41.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 329.57906795835447
> flash tech bufferLength: 1
> flash tech bufferEnd: 324.94706795835447
> segment end: 324.94706795835447
> 
> high720p45.ts
> pendingSegment_ bufferLength: 0
> VIDEOJS: Error: This TimeRanges object is empty(…)
> 
> high720p51.ts
> pendingSegment_ bufferLength: 0
> 
> high720p60.ts
> pendingSegment_ bufferLength: 0
> VIDEOJS: Error: This TimeRanges object is empty(…)
> 
> // FLASH BUFFER END AND SEGMENT END ARE INCORRECT HERE!
> high720p66.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 466.53114756878034
> flash tech bufferLength: 1
> flash tech bufferEnd: 466.53114756878034
> segment end: 466.85014756878036
> duration change: 672.9701475687804
> 
> high720p77.ts
> pendingSegment_ bufferLength: 0
> 
> // FLASH BUFFER END AND SEGMENT END ARE INCORRECT HERE!
> high720p78.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 559.2134902864942
> flash tech bufferLength: 1
> flash tech bufferEnd: 551.2494902864942
> segment end: 551.2494902864942
> duration change: 661.3294902864942
> 
> high720p80.ts
> pendingSegment_ bufferLength: 0
> VIDEOJS: Error: This TimeRanges object is empty(…)
> 
> // FLASH BUFFER END AND SEGMENT END ARE INCORRECT HERE!
> high720p83.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 564.7755900818382
> flash tech bufferLength: 1
> flash tech bufferEnd: 588.7985900818383
> segment end: 588.7985900818383
> duration change: 658.8785900818383
> 
> high720p84.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 588.7985900818383
> flash tech bufferLength: 1
> flash tech bufferEnd: 596.8095900818382
> segment end: 596.8095900818382
> duration change: 658.8895900818383
> 
> high720p85.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 596.8095900818382
> flash tech bufferLength: 1
> flash tech bufferEnd: 604.7965900818382
> segment end: 604.7965900818382
> duration change: 658.8765900818382
> 
> high720p86.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 604.7965900818383
> flash tech bufferLength: 1
> flash tech bufferEnd: 612.8085900818381
> segment end: 612.8085900818381
> duration change: 658.8885900818382
> 
> high720p87.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 612.8085900818382
> flash tech bufferLength: 1
> flash tech bufferEnd: 620.7955900818383
> segment end: 620.7955900818383
> duration change: 658.8755900818384
> 
> high720p88.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 620.7955900818382
> flash tech bufferLength: 1
> flash tech bufferEnd: 628.8065900818383
> segment end: 628.8065900818383
> duration change: 658.8865900818383
> 
> high720p89.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 628.8065900818382
> flash tech bufferLength: 1
> flash tech bufferEnd: 636.7935900818383
> segment end: 636.7935900818383
> duration change: 658.8735900818383
> 
> high720p90.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 636.7935900818381
> flash tech bufferLength: 1
> flash tech bufferEnd: 644.8045900818382
> segment end: 644.8045900818382
> duration change: 658.8845900818383
> 
> high720p91.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 644.8045900818383
> flash tech bufferLength: 1
> flash tech bufferEnd: 652.7925900818382
> segment end: 652.7925900818382
> duration change: 658.8725900818382
> 
> high720p92.ts
> pendingSegment_ bufferLength: 1
> pendingSegment_ bufferEnd: 652.7925900818383
> flash tech bufferLength: 1
> flash tech bufferEnd: 659.0615900818382
> segment end: 659.0615900818383

I find that the duration is calculate by using the segment.end value, most of time using the `backwardDuration()` function to calculate, and the incorrect end of segment result in incorrect duration. The incorrect segment end time seems to come from the flash buffered time depending on that log above. I find that there are four places where could trigger the 'updateend' event. This where I could debug so far.

If more information needed, I will try to provide as much as I can.
Thanks in advance.

P.S. Sorry for my broken english.  I hope I illustrate the issue clearly enough...

**Comment by gesinger** [comment] 2017-04-07 22:08
Hey @cagen , sorry this ticket has gone a long time without much attention, and thanks for all of the detailed debugging info. We've made a lot of changes to videojs-contrib-hls in the meantime, and I noticed that the original streams are down. Would you be able to give the latest version of videojs-contrib-hls a shot (as of this comment, v5.4.0), and if you're still seeing issues, let us know what source your are using? Thank you.

**Comment by gesinger** [comment] 2017-04-14 15:05
Closing for now. If you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.4.1), please re-open the issue and, if possible, provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output), and/or the source you are using. Thanks again for all of the debugging info.

**Closed by gesinger** 2017-04-14 15:05 UTC
Labels: needs:info

**Comment by cagen** [comment] 2017-04-26 06:39
@gesinger Sorry for my late reply.
I checked the lastest stable version of the video.js(v5.19.2) and videojs-contrib-hls(v.5.5.0)，I cannot reproduce the issue anymore. I think it was fixed already.
If anyone interested, here is the new example which seems to work pretty well:
https://plnkr.co/edit/DsVoSLIyhw6vbvk7PC6E?p=preview

And since the [flash tech has been removed](https://github.com/videojs/video.js/pull/3956) from the video.js v6.0.0, maybe it was not a problem in the future?

**Comment by gesinger** [comment] 2017-04-26 14:29
Thanks for the update @cagen. And yeah, since the flash tech is no longer there by default in video.js v6 (and must be added via the videojs-flash plugin), I imagine that even if the issue is present somewhere for flash, it will be less of a concern.
