### ISSUE TITLE
InvalidStateError calling endOfStream for broken source urls in chrome

### ISSUE THREAD

**Issue by t-n** [videojs/videojs-contrib-hls#575] opened 2016-03-01 14:58 UTC
When using a video source that is returning a 404 or connection refused I get no error event but instead get an uncaught InvalidStateError.

```
Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.
videojs.HlsHandler.blacklistCurrentPlaylist_ @ videojs-hls.js:1129
(anonymous function) @ videojs-hls.js:189
trigger @ stream.js:60
(anonymous function) @ playlist-loader.js:326
(anonymous function) @ xhr.js:42
(anonymous function) @ index.js:8
loadFunc @ index.js:145
readystatechange @ index.js:75
```

Steps to reproduce:
1. Put videojs-contrib-hls(1.3.9) on a web server.
2. Open example.html in Chrome(48).
3. Change the video url to a vaild non-existing url, e.g. changing just the domain name to the same domain name/ip and port as the webserver. (with valid CORS headers)

Expected result:
- An error event (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) with the corresponding message in the player.

Actual result:
- Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.
  (If you try to load the video url a second time the correct event is triggered if it's a 404 but not if it's a connection refused)

**Comment by sashee** [comment] 2016-03-08 10:21
This just bit me too. Could you find a workaround?

**Comment by t-n** [comment] 2016-03-08 11:41
No, not yet.

**Comment by ZacharySato** [comment] 2016-08-29 14:23
Having the same issue. 
I try to bind player rebuilding on 'error' event, but in this case 'error' isn't actually triggered. 
Strange thing is that 'InvalidStateError' appears randomly across correct 'CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED'.

**Comment by mrmckeb** [comment] 2016-11-07 00:37
We're also seeing this issue intermittently, but it doesn't appear to be causing any actual problems in the video streams.

**Comment by askaliuk** [comment] 2016-11-21 22:06
I confirm this issue

**Comment by gesinger** [comment] 2017-01-21 00:25
I see a lot of people have seen this issue as well. I tried the listed steps with the latest player, but was unable to reproduce the problem. Would someone who is seeing the issue be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/edit?html,output)?

Thank you all for reporting the issue.

**Comment by aquu** [comment] 2017-01-23 13:00
@gesinger I just noticed that I can reproduce that error if I get 404 response straight from the streaming server (in my case Wowza) but if url points to cloudfront (as in that template), then videojs handles it right.

**Comment by gesinger** [comment] 2017-01-23 15:38
@aquu , do you happen to have a stream we can test with?

**Comment by aquu** [comment] 2017-01-23 18:18
@gesinger I tested it on another computer and I can't reproduce it now with our servers.. However I get same error when hosting that template code with php.

I'm running local server on Ubuntu 16.04 with `php -S localhost:8000` and when I open browser I get following on the console. No 404 error is thrown.

![image](https://cloud.githubusercontent.com/assets/6368209/22216762/03e87e72-e1a9-11e6-8643-3f5c4f775633.png)

**Comment by poohitan** [comment] 2017-01-31 16:07
Same issue.

**Comment by gesinger** [comment] 2017-01-31 17:52
While I haven't yet been able to create a reproducible test case, when running a local server with the template I saw it happen now and again on refreshes. Probably related to a timing issue.

**Comment by AndriyOleksyuk** [comment] 2017-02-24 12:58
The same issue for me.
For me it is critical situation because i can not catch error from player and handle it.
More info:
On PC player request for playlist.m3u8 and first chunklist even when preload set to "none". But it should not to do it (you can check how it works on mobile). And if machine for request for playlist.m3u8 is unavailable we will have error described above.  

So preload is also important thing. Because if you have few players on page each of them makes 2 unnecessary request even before any player start to play. Thats is not good for analytics and performance.

**Comment by gesinger** [comment] 2017-02-28 17:45
We are currently working on a fix for this issue. We will link a pull request as soon as we have one ready. Thanks again for the reporting and all of the activity.

**Comment by poohitan** [comment] 2017-03-14 12:36
@gesinger how are things going with this issue?

**Comment by gesinger** [comment] 2017-03-24 01:37
Hey @poohitan , sorry for the delay. Just submitted the PR. We'll try to get it reviewed soon.

**Comment by poohitan** [comment] 2017-03-24 08:27
@gesinger cool, waiting for it to be merged. Thanks for the effort!

**Comment by gesinger** [comment] 2017-04-11 15:46
Thanks again for everyone reporting the issue and adding more information. videojs-contrib-hls v5.4.1 was released yesterday which included PR https://github.com/videojs/videojs-contrib-hls/pull/1061. Now a proper player error should be triggered even if the MediaSource is not ready (we catch the thrown exception and manually trigger a player error ourselves). There is still a known bug around the player sometimes clearing the error overlay ( https://github.com/videojs/videojs-contrib-hls/issues/1079 ), however, the error event is now properly thrown and no exception is triggered.

**Closed by gesinger** 2017-04-11 15:46 UTC
Labels: bug, confirmed, inprogress

**Comment by icetronics** [comment] 2017-05-16 15:53
Hi @gesinger! Thanks for the fix though I experience that the standard error media event does not get triggered on the underlying video element. Is that possible? Is there another way to attach an error handler on the player? Thank you in advance!

**Comment by rishigohil** [comment] 2017-06-15 14:58
I am having the same issue and it seems that it's not handled with the latest release. The video keeps on loading and does anyone know if we can handle this error from our end until we get support from the plugin? Or am I missing something?

![image](https://user-images.githubusercontent.com/5967748/27187507-637fbca8-51b9-11e7-83ae-705e50c64db6.png)
