### ISSUE TITLE
HLSv3 (muxed sources) stalls after preroll

### ISSUE THREAD

**Issue by martinstender** [videojs/videojs-contrib-hls#1145] opened 2017-06-02 15:07 UTC
## Description
I have a 'all-in-the-family' setup with videojs, contrib-ads and contrib-hls here:

https://codepen.io/martinstender/pen/KmLLxV?editors=1011

The issue is, that after a preroll ends and content should resume, any m3u8 with muxed sources play the first few frames, then stalls for quite a few seconds.

An interesting note is that **sometimes** it plays nicely the first time, but all following attempts has the issue. I don't know if that can spark any ideas about what is going on... 

## Steps to reproduce

1. Open the codepen, hit run and optionally hit the 'skip ad' button when possible 
2. Comment out line 15 and comment in line 12 (in codepen html-editor, place cursor in the line and hit cmd+'/'
3. Run the pen again and things runs fine.
4. Go to line 18 in the javascript editor and change `playAds` to `false` - then both sources runs fine.

### Expected
I hoped all standard HLSv3/4 would work...

### Error output
In the network panel (XHR selected), after content resumes, the **second** .ts-segment is cancelled after the first one is loaded successfully and then everything is requested again (0000, 0001 etc.).
This is very consistant. (The AWS bucket is in Ireland, I'm in Copenhagen, so it may change depending on your location)

### videojs-contrib-hls version
videojs-contrib-hls 5.5.0

### videojs version
video.js 6.0.0

### Browsers
As far as I have noticed, all recent browser version have the issue. (Chrome, Firefox, Safari)

### Platforms
MacOs

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* contrib-ads 4.2.6-0

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* none

**Comment by gesinger** [comment] 2017-06-02 16:58
Hey @martinstender , thanks for the issue, but this looks like it has to do with contrib-ads rather than contrib-hls (contrib-ads might be seeking as it restores the state, thereby clearing the buffer  after contrib-hls may have started playing, leading to a stall as it reloads content). I think it might be better as an issue on that repo rather than here, unless this can be replicated with contrib-hls without the addition of contrib-ads.

**Comment by martinstender** [comment] 2017-06-02 18:35
Thank you for your answer.
I already posted an almost identical issue on contrib-ads, but I was kinda sent over here... :-)

If nothing else, this post might reach someone who is not on Slack and might have experienced something similar.

Best regards 
Martin

**Comment by gesinger** [comment] 2017-06-09 21:04
Hey @martinstender , I see the issue posted at https://github.com/videojs/videojs-contrib-ads/issues/263 .

Is there any chance you might be able to reproduce the issue without the contrib-ads plugin (using just our [starter template](http://jsbin.com/vokipos/8/edit?html,output) )? If so, then we can definitely take a look at it here. Otherwise, I think we should close this one in favor of the other issue.

**Comment by gesinger** [comment] 2018-03-02 22:59
Closing for now. If you are still experiencing this issue with the latest versions of videojs-contrib-hls and videojs-contrib-ads, please let us know. Thank you.

**Closed by gesinger** 2018-03-02 22:59 UTC
Labels: needs:info
