### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

### ISSUE THREAD

**Issue by qnlpkuge1** [videojs/videojs-contrib-hls#1247] opened 2017-08-29 11:40 UTC
## Description
I am having problems watching videos in some webpages. I get the error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.". This only happens on certain websites, The problem startet a couple of weeks ago, and i cant seem to find a fix on the web. Any suggestions on how to fix this?

## Sources
error like this 
https://www.snotr.com/video/18694/Wrong_Place_Wrong_Time

## Steps to reproduce
When using VideoJS HLS, I always open the Developer Tool in Chrome to
find errors :)

I also use h264 which has support to
generate HLS stream. I can watch the generated HLS stream in Safari.
Unfortunately, I got the following errors in Chrome:

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was
aborted due to a corruption problem or because the media used features
your browser did not support.

### Expected
I get the error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.".

### videojs-contrib-hls version
videojs-contrib-hls 3.5.3

### videojs version
video.js 5.15.1

### Browsers
chrome 

### Platforms
windows 7

**Comment by joshuairl** [comment] 2017-09-14 20:24
Also having this issue, anyone know what to do?  I'm using videojs-contrib-hls 5.10.1.

**Comment by bnussey** [comment] 2017-09-21 03:42
Also having same issue, upgraded to `5.11.0` but still seeing it. Thanks.

**Comment by savokiss** [comment] 2017-09-28 12:52
Also having the same issue, use chrome on win10.....

**Comment by hayatbiralem** [comment] 2017-10-06 16:01
I use Win10 and Chrome, and I have the same problem.

**Comment by azizantoun** [comment] 2017-10-06 16:55
Same here.

**Comment by mjneil** [comment] 2017-10-11 20:42
This specific source has multiple video tracks within the stream. Previously we did not account for multiple tracks, so data from all tracks were being merged together resulting in playback errors or distortion. v5.11.1 of videojs-contrib-hls will now use only a single audio/video track when multiple are present to prevent the distortion. Closing this for now as fixed. If you continue to experience problems please re-open or submit a new issue.

**Closed by mjneil** 2017-10-11 20:42 UTC

**Comment by hiepnm** [comment] 2017-11-06 07:08
The same issuse.
videojs-contrib-hls: 5.12.1.
Mac OSX Sierra and Chrome.

**Comment by morkov4o** [comment] 2017-11-15 20:43
any update ? we face the same problem ? is`t fixed ?

**Comment by chianhsieh** [comment] 2018-01-27 16:42
Hello,

I also faced this problem after I upgraded to Chrome 64.0.3282.119. ( before this version of Chrome, there is no problem on it)

Here are the details about the errors: 
( I used the latest versions which are Videojs 6.6.3 and videojs-contrib-hls 5.12.2 )

`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}`

`VIDEOJS: ERROR: (CODE:-3 undefined) Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null. `

And more details about the above errors:

```
MediaError {code: -3, type: "APPEND_BUFFER_ERR", message: "Failed to execute 'appendBuffer' on 'SourceBuffer'…The HTMLMediaElement.error attribute is not null.", originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribu…}code: -3message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
    at Object.wrapper.(anonymous function) [as appendBuffer] (/js/videojs-contrib-hls.js.2:19810:34)
    at VirtualSourceBuffer.concatAndAppendSegments_ (/js/videojs-contrib-hls.js.2:20527:29)
    at VirtualSourceBuffer.processPendingSegments_ (/js/videojs-contrib-hls.js.2:20475:14)
    at VirtualSourceBuffer.done_ (/js/videojs-contrib-hls.js.2:20202:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (/js/videojs-contrib-hls.js.2:20013:22)code: 11message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."name: "InvalidStateError"stack: (...)get stack: ƒ nativeGetter()set stack: ƒ nativeSetter()__proto__: DOMExceptiontype: "APPEND_BUFFER_ERR"__proto__: Object
logByType @ videojs.6.6.3.js:498
log.error @ videojs.6.6.3.js:620
error @ videojs.6.6.3.js:23525
concatAndAppendSegments_ @ videojs-contrib-hls.js.2:20530
processPendingSegments_ @ videojs-contrib-hls.js.2:20475
done_ @ videojs-contrib-hls.js.2:20202
VirtualSourceBuffer.transmuxer_.onmessage @ videojs-contrib-hls.js.2:20013
```

Could any one have any ideas on this? 

Many Thanks.

**Comment by SolmazKh** [comment] 2018-02-06 10:57
I am having the same problem. V  5.12.2
Any updates about this issue?

**Comment by zhangzs000** [comment] 2018-03-26 09:07
i have the some problem Video.js 6.2.8

**Comment by sumeetkate** [comment] 2018-04-05 18:09
Hi Folks,
Is there update on the issue ?

**Comment by vakuzmin** [comment] 2018-05-23 12:53
the same issue

**Comment by SuYuWei** [comment] 2018-06-22 08:04
same issue

**Comment by liupeng5843** [comment] 2018-06-23 07:13
the same issue

**Comment by IhorVimmi** [comment] 2018-07-23 13:53
Opera 54.0.2952.60 Ubuntu 16.04 same issue

**Comment by bogatisuman** [comment] 2018-08-09 08:34
Same issue on Chrome of Android(kitkat).

**Comment by dannyf620** [comment] 2018-09-12 22:56
the problem is in the Streaming signal and not in the player, sometimes it happens after a specific time, consult the problem with the streaming provider. To verify try with another different signal and you will see the difference,
verify whit chorme or firefox device simulator without some player direct url 'inspect'

**Comment by UniqueMarvin** [comment] 2018-09-18 02:58
Same issue on Chrome，but the same media file is OK on flash of IE 11 win7
