### ISSUE TITLE
Playback hangs with 'loading' spinner in Chrome beta (55) when trying to start certain segments.

### ISSUE THREAD

**Issue by Ambroos** [videojs/videojs-contrib-hls#916] opened 2016-11-16 15:40 UTC
## Description
We are working on HLS streams that include dynamically inserted advertisements. Our current setup works, but videojs-contrib-hls consistently hangs in Chrome (only the current v55 beta) when it encounters some segments, and I can't figure out why.

If I try to play just the 'bad' segment everything is fine, and if I change the order everything is fine too. It's just with these segments in this specific order, only on Chrome macOS, that the playback stops.

Example: https://medialaan.ambroos.io/hls-discontinuity-chrome-hang/
Playback will hang at 0:36 in Chrome v55 (beta), but work on other versions/browsers.

## Sources
Playlist: https://medialaan.ambroos.io/hls-discontinuity-chrome-hang/short-test-stream.m3u8 (CORS open, so can be tested everywhere)

It only seems to appear with the segments in exactly this order.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the linked HLS playlist in Chrome Beta (v55)
2. Wait until after the second (Coca Cola) ad (0:36)
3. The player stops playback and a loading spinner is displayed.

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 3.6.12

### videojs version
what version of videojs does this occur with?
video.js 5.12.6

### Browsers and platforms
Chrome Beta v55 on macOS 10.12.2 and Windows 10 (latest)

Chrome Stable (v54) and Dev/Canary (v56+) do not have any issues.

### Other Plugins
None.

### Other JavaScript
None.

**Comment by RavWar** [comment] 2017-01-13 19:13
I can confirm this bug on Chrome 55 (which is now stable).
Test link: https://raw.githubusercontent.com/RavWar/RavWar.github.io/master/sample.m3u8

If i test it here: http://videojs.github.io/videojs-contrib-hls/, it hangs after 4 seconds, right between 2 chunks.
Hls.js demo http://dailymotion.github.io/hls.js/demo/ plays it just fine.

I work with a lot of hls streams and this problem occurs in a fair amount of them, multiple times per stream.
Can someone help get to the bottom of this?

**Comment by masterful** [comment] 2017-01-20 20:21
I was also able to reproduce this. It looks like the difference may have something to do with the duration/timing of the two chunks.

According to chrome://media-internals -> the contrib-hls approach has the following:
```
	Generated splice of overlap duration 3166us into new buffer at 4156833us.
```
While hls.js does not.

I tried re-encoding the segments with ffmpeg (first combined and then re-split):
https://masterful.github.io/test-pages/stream-test/sample.m3u8

This one works on the contrib-hls but stutters between the two segments - so perhaps the issue is coming from the mux library?

**Comment by ip** [comment] 2017-01-25 06:36
Hello, I'm trying to fix this bug. I used the sample @RavWar provided. That's what I found so far.

There is following sequence of events on the `<video>` element until hang moment:
```
play
playing
timeupdate
durationchange
durationchange
durationchange
timeupdate
timeupdate
...
timeupdate
stalled
timeupdate
timeupdate
timeupdate
waiting
```

According to [description of `waiting` event](https://html.spec.whatwg.org/multipage/embedded-content.html#event-media-waiting), `Either seeking is true, or the current playback position is not contained in any of the ranges in buffered.`
So I have inspected the state of player's `HTMLMediaElement` object (it is the same as `<video>` element) at the moment of lag:
- `seeking === true`
- `buffered` includes the whole video interval - from 0 to 8.341666
- `seekable` interval is the same

Also:
- `error === null`
- `networkState === NETWORK_LOADING`

Maybe this can help. I'll continue to explore it.

**Comment by ip** [comment] 2017-01-25 06:39
Here is a snippet for Chrome that I used for event logging:
```js
let video = player.children()[0]

let eventNames = [
    'durationchange',
    'loadedmetadata',
    'loadeddata',
    'canplay',
    'canplaythrough',
    'ended',
    'emptied',
    'stalled',
    'suspend',
    'play',
    'playing',
    'pause',
    'waiting',
    'seeking',
    'seeked',
    'ratechange',
    'timeupdate',
    'volumechange',
    'complete',
    'ended',
    'audioprocess'
]

eventNames.forEach((event) => {
    video.addEventListener(event, () => {
        console.log('<video> event triggered: ', event)
    })
})
```

**Comment by masterful** [comment] 2017-01-25 11:58
So there are some handlers [around here](https://github.com/videojs/videojs-contrib-hls/blob/e8ebb58a2380814400b77e80b36caeac86269b4d/src/playback-watcher.js#L130) for when playback enters a `waiting` state. At the moment they have to do with checking for underflow or gaps, but if I had to guess it looks like the two segments are actually overlapping ever so slightly, which causes issues moving to the next segment?

If we're able to detect this better we could probably modifying this section to poke the video along a short amount (a second or so) and have it resume playback...

**Comment by ip** [comment] 2017-01-27 20:09
@masterful I just tried your suggestion with this snippet and it kinda works:
```js
(() => {
    let video = player.children()[0]

    let listener = () => {
        console.log('waiting event')
        video.currentTime += 0.25 / 2
    }
    video.addEventListener('waiting', listener, { once: true })
})()
```
But there is blinking loading indicator and this is pretty rough hack. Also, it works in my case only with a given delay (0.25 / 2) or bigger and I haven't figured out why.

**Comment by masterful** [comment] 2017-01-27 21:43
The delay size (0.125s) might be related to finding a useable keyframe to jump to. But that's just a guess. I think the ideal solution would be to figure out why the segments are causing that overlap in the first place, as I agree that the `waiting` handler is an ugly (although effective) workaround.

**Comment by ip** [comment] 2017-01-27 21:50
This bug doesn't exist in Chrome 56, which is now stable. Does it still make sense to fix it?

**Comment by gesinger** [comment] 2017-03-21 19:35
Sorry this ticket has gone a long time without much attention.

As @ip said, now that Chrome stable is past 55, and doesn't present the problem anymore (I can't reproduce the issue with the provided test streams), it sounds like the issue was addressed at the browser level.

We've also made a lot of changes to videojs-contrib-hls in the meantime. Closing for now, but If anyone is still experiencing this issue, please let us know. Thank you for reporting the issue, and for all of the debugging info.

**Closed by gesinger** 2017-03-21 19:35 UTC
