### ISSUE TITLE
Bug with m3u8 URL with Token

### ISSUE THREAD

**Issue by mikhoul** [videojs/videojs-contrib-hls#1018] opened 2017-02-17 19:54 UTC
## Description

I need to pass a Token/Argument with m3u8 URL and it fail to take it.

Here's the Error in the console I receive:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }  video.js:22933:5
	logByType https://unpkg.com/video.js/dist/video.js:22933:5
	[86]</log.error https://unpkg.com/video.js/dist/video.js:22969:10
	error https://unpkg.com/video.js/dist/video.js:11664:5
	handleTechError_ https://unpkg.com/video.js/dist/video.js:10434:5
	bound https://unpkg.com/video.js/dist/video.js:22721:12
	bound https://unpkg.com/video.js/dist/video.js:22721:12
	on/data.dispatcher
```

Here's the URL I try: http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1487360627~exp=1487360717~acl=/i/tvago_1@410563/*~hmac=ed1b43b9dc58ecde70783302b2b2e6637afc3ae6f8fad35e50e0eb31e5fcd62e

If you want to generate a new valid token just go here: http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go here: http://videojs.github.io/videojs-contrib-hls/#
2. Load URL with a valid Token

## Additional Information

Work fine in other player like SMP player or Grind Player.

### Browsers

Latest Firefox and Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Win 7/64

Regards :octocat:

**Comment by gesinger** [comment] 2017-02-17 20:01
Hey @mikhoul , thanks for posting the stream. Usually that error indicates a problem downloading either the m3u8 file(s) or the segment(s). I tried to go there myself to see the playlist but just got "Access Denied You don't have permission to access "http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?" on this server."

**Comment by gesinger** [comment] 2017-02-17 20:18
After generating a new token I was able to play the stream in the player at http://videojs.github.io/videojs-contrib-hls/# .

**Comment by mikhoul** [comment] 2017-02-17 20:47
Thanks for the help @gesinger ,

Here's a screenshot of what happen when I enter the full URL "http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1487363778~exp=1487363868~acl=/i/tvago_1@410563/*~hmac=3c8f8f06910cdcbc7779ee67c659254001518c3a23d30fb2e8f1a7d242b46625" and press "Load"

**In Firefox:** http://i.imgur.com/Pn1aM0y.png + http://i.imgur.com/GbnPoli.png

**In Chrome:** TS Fragment are loading but I have a Black Screen: http://i.imgur.com/ZI6sj48.png

What I'm doing wrong ?


Regards :octocat:

**Comment by gesinger** [comment] 2017-03-29 00:00
Hey @mikhoul , I noticed that in the Firefox screenshot you are getting 403 forbidden responses for the segment requests. That looks like it must be a problem either with the server, or with the credentials/client requesting the segments. I also noticed that in the Chrome screenshot those requests are for the manifest refreshes (since it is a live stream), not for TS fragments (one way you can tell, even without the full URL, is that the requests seem to be at 10 second increments which is the target duration for that stream). I am still able to play the stream in the example page after generating a new token. Would you be able to give it another shot? Thanks.

**Comment by mikhoul** [comment] 2017-03-29 01:05
Hi @gesinger ,

I tried again but I have the same results with both Firefox and Chrome.

I can confirm that the Stream is not the problem since I have no problem at all playing the  stream with [FlasHLS](https://github.com/mangui/flashls) with [Video-js-swf](https://github.com/mangui/video-js-swf) on Firefox or Chrome.

If you need more information just ask.

Regards  :octocat:

**Comment by gesinger** [comment] 2017-04-05 23:11
Hey @mikhoul , I gave it another shot in the environment you mentioned (Chrome on Windows 7) and it worked for me there too. I still haven't been able to replicate the issue. It's possible that it could be related to some Chrome config or plugin, or possibly a network related issue that you are experiencing when using Chrome.

**Comment by aranondo** [comment] 2017-04-06 07:59
Same happened to me and the solution was to use "hls: {withCredentials: true}" when creating the videojs object. Without that option the response from the server was a 403 because of the access control allow origin header. Could you try that?

**Comment by mikhoul** [comment] 2017-04-06 15:26
@aranondo 

I don't know how to do that exactly, could you show me with an example on JsBin ?

Regards ! :octocat:

**Comment by aranondo** [comment] 2017-04-07 07:02
@mikhoul Sorry I don't know why it's not working in jsbin. Here is the code in pastebin, you can use is as html and works fine por me https://pastebin.com/qBmUW089
Change the src with a valid one.

**Comment by gesinger** [comment] 2017-04-14 17:34
Hey @mikhoul , have you been able to find the source of the issue? I still haven't been able to reproduce the problem. Would you be able to give it a shot on a different machine?

**Comment by gesinger** [comment] 2017-04-21 14:13
Closing for now. If you are still experiencing this issue, please give it a shot on another machine and let us know if the result is the same. If it is, let us know if you took any different steps to reproduce the problem. Thanks.

**Closed by gesinger** 2017-04-21 14:13 UTC
Labels: needs:info
