### ISSUE TITLE
hls.xhr.beforeRequest seems do not work properly

### ISSUE THREAD

**Issue by md2k** [videojs/videojs-contrib-hls#665] opened 2016-04-22 19:00 UTC
Hi Guys, i tried release 2.1.1 (over npm) and found that `beforeRequest` work correctly only:
- if I set it globally as videojs.Hls.xhr.beforeRequest
- if I set it during playback with `player.tech({ IWillNotUseThisInPlugins: true }).hls.xhr.beforeRequest`

But if i trying set it as:

```
player.hls.xhr.beforeRequest = function(options) {
  options.uri = options.uri.replace('example.com', 'foo.com');

  return options;
};
```

I see nothing.
My app loading video programmatically, application do next steps to play:

```
function _play(vObj, data) {

   // some magic about vObj - data about stream with source and some other params
   // _api is videojs api
  _api.src({ type: "application/x-mpegurl", src: url, withCredentials: true});
  _api.hls.xhr.beforeRequest = function(options) {
      console.log(options);
      return options;
   };
   api.load();
   api.play();
}
```

Maybe i do something wrong, but as i said above , was succeed only with Globally defined function or already when playback starts, assigning function to player before playback didnt call this functionality.

**Comment by sdcoca** [comment] 2016-06-15 15:51
Have similar issue. And see two additional unexpected behaviours:

- If videojs.Hls.xhr.beforeRequest is changed, then it is never called since a copy of it seems to be used instead of the actual. Thus, if not updated before it is copied (which I cannot manage to do) then it is ignored.
- When the player switches sources, the player.hls.xhr hook gets removed as if it was a new player instance.

**Comment by whatvn** [comment] 2016-06-17 03:50
with newest version I no longer can override xhr. beforeRequest by writing my own videojs.Hls.xhr. beforeRequest function. 

The only way to do this is override that function at runtime : `player.hls.xhr.beforeRequest`. 
And as described in contribute hls doc, we also can override hls.xhr, although it's not recommended, but it's possible. With previous version of contrib-hls, i can override xhr by writing my own videojs.Hls.xhr, but now it's not possible too. 
Any idea?

**Comment by apatinoyu** [comment] 2016-11-04 12:02
Hello. Di you fix it? I am trying to set it as a global variable videojs.Hls.xhr.beforeRequest = function (options) {
//here I add my headers
}
but no success

**Comment by kazazes** [comment] 2016-11-16 17:31
I'm also experiencing this regression. My `videojs.hls.xhr` overridden function used to be called, now it isn't.

**Comment by kazazes** [comment] 2016-11-16 17:55
@whatvn @apatinoyu @sdcoca, overriding the method on a per-player instance works. Try `player.tech_.hls.xhr = videojs.Hls.xhr` after initializing the player. Note, the player should already have an HLS stream as a source before this point or it won't have the `hls` tech. For whatever reason videojs is always loading the HLS methods from the defaults, even if they're overridden.

**Comment by apatinoyu** [comment] 2017-01-03 10:20
Hi @kazazes, thanks for the help, did you test on Safari or Edge (those Browsers have Native Hls support )? 

I made it working with the current version `hls-contrib @version 4.0.2`, `beforeRequest` is called adding this line to confirm the override Native `videojs.options.hls.overrideNative = true;` 
Did not work on Safari, Edge.

**Comment by gesinger** [comment] 2017-01-26 23:38
PR created https://github.com/videojs/videojs-contrib-hls/pull/983

**Comment by gesinger** [comment] 2017-04-11 15:39
Thanks again for reporting the issue, and for everyone adding on with more information. Yesterday v5.4.1 was released with PR https://github.com/videojs/videojs-contrib-hls/pull/983 included. `beforeRequest` is now no longer copied when a new HLS instance is created, but is instead read live from the HLS instance when requests are made. This means that `player.hls.xhr.beforeRequest` and `videojs.Hls.xhr.beforeRequest` can be changed as a source is playing. As before, if you want to have a per player per source modified `beforeRequest`, please use `player.hls.xhr.beforeRequest`, and if you want to have a global modified `beforeRequest`, please use `videojs.Hls.xhr.beforeRequest`. Thanks.

**Closed by gesinger** 2017-04-11 15:39 UTC
Labels: bug, confirmed, inprogress
