### ISSUE TITLE
player.ended() false when replaying after media source is ended

### ISSUE THREAD

**Issue by dmlap** [videojs/videojs-contrib-hls#522] opened 2016-01-19 16:21 UTC
Even though mediaSource.endOfStream() is being called and the Media Source's `readyState` is `ended`, the HTML tech reports that it is not ended when the `play` event fires on replay. That means we never "seek" back to the first segment and the player keeps spinning.

Seen on Chrome and Firefox with 1.3.4.

**Comment by imbcmdth** [comment] 2016-01-21 22:32
Can't reproduce!

**Comment by shanepoints** [comment] 2016-02-02 00:38
This is causing me pains as well.  The player does not seek to the beginning, but the larger problem is that I cannot bind any actions using the vjs 'ended' event: 
`Player.on('ended', function(){
   //Do something when the video ends
});`

**Comment by ravi155** [comment] 2016-02-03 08:47
+1

**Comment by shanepoints** [comment] 2016-02-10 00:22
I seem to have isolated this problem to situations where the Player instance has called the dispose() method and then re-initialized a new player.  

For example, I have a playlist on a page.  Clicking on a video in the playlist calls dispose() on the current Player and then re-inserts a new video tag and initializes a new player instance. The 'ended' event is registering properly for the first video that loads... however the second video(and subsequent videos) will not register this event.

This issue is only encountered when loading an HLS stream.  It cannot be reproduced when mp4 or webm are in use.  Tested on latest versions of Chrome and Firefox.

**Comment by forbesjo** [comment] 2016-09-01 19:53
We tested this on the advanced player page at http://videojs.com/advanced/ switching with the sintel HLS source and ended fired both times. Is this still an issue, if so could you provide a reduced test case?

**Comment by gesinger** [comment] 2017-01-20 18:33
Closing since we can't reproduce. Please re-open if this is still an issue on the latest player, and please provide a reduced test case using [this template](http://jsbin.com/liwecukasi/edit?html,output) if you can. Thank you.

**Closed by gesinger** 2017-01-20 18:33 UTC
Labels: needsinfo
