### ISSUE TITLE
Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by gskalyan90** [videojs/videojs-contrib-hls#1277] opened 2017-10-11 16:12 UTC
## Description

I am getting this issue "Uncaught TypeError: Cannot read property 'byteLength' of undefined" when we are playing our HLS source

## Sources
https://vhoichoi.viewlift.com/encodes/115/hls/master.m3u8

## Steps to reproduce
Play this video https://vhoichoi.viewlift.com/encodes/115/hls/master.m3u8 at https://videojs.github.io/videojs-contrib-hls/

### Error output
Uncaught TypeError: Cannot read property 'byteLength' of undefined
    at VirtualSourceBuffer.processPendingSegments_ (videojs-contrib-hls.js:19878)
    at VirtualSourceBuffer.done_ (videojs-contrib-hls.js:19639)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (videojs-contrib-hls.js:19458)
## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls
videojs-contrib-hls 5.5.3

### videojs version
what version of videojs does this occur with?
video.js 5.19

### Browsers
what browsers are affected? please include browser and version for each
* chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*MAC

**Comment by gesinger** [comment] 2018-03-13 21:12
Sorry this issue has gone a while without much attention. It looks like that stream may be down (or behind protection). Are you still experiencing this issue with the latest version of videojs-contrib-hls, and if so, would you be able to bring the stream back up (slash make it accessible)? Thank you.

**Comment by gesinger** [comment] 2018-03-16 17:21
Closing. If you are still having issues with the latest release of videojs-contrib-hls, please let us know (and provide a new source if possible). Thank you.

**Closed by gesinger** 2018-03-16 17:21 UTC
Labels: needs:info

**Comment by gaxunil** [comment] 2018-08-02 00:17
Thanks yeah I don't have a great consistent way to reproduce this yet and we are continuing our investigations across the stack, thanks so much for the info @gesinger !!
I will let you know if I see something valid in our findings that indicates a bug.
