### ISSUE TITLE
segment is undefined if endSequence > playlist.mediaSequence

### ISSUE THREAD

**Issue by oldcookie** [videojs/videojs-contrib-hls#312] opened 2015-06-16 16:22 UTC
In playlist.js, on the call to `segmentsDuration`, and exception is thrown if endSequence > playlist.mediaSequnce.  This causes a -ve array index in the following code.

```
 for (; i < endSequence; i++) {
      segment = playlist.segments[i - playlist.mediaSequence];
      result += segment.preciseDuration ||
                segment.duration ||
                targetDuration;
 }
```
see
https://github.com/videojs/videojs-contrib-hls/blob/24ab14028ddf6215d57601b0d5618002093b6ff3/src/playlist.js#L38-41

Not quite sure what is the right way to fix it though...

**Comment by dmlap** [comment] 2015-06-16 21:47
Do you mean when `i < playlist.mediaSequence`?

**Comment by oldcookie** [comment] 2015-06-17 01:28
What I mean is, when `endSequence > playlist.mediaSequence`, then eventually, `i > playlist.mediaSequence`.  This would result in i < 0, hence a -ve index

**Comment by oldcookie** [comment] 2015-06-17 01:34
Actually, I think I read the values wrong.  Will have to test it again tomorrow.   Then end result is that `segment` is `undefined`.  So `segment.preciseDuration` causes an exception.  Not sure if I can fix this by checking if segment is defined, or if the sequence needs to be fixed.  Will test and update tomorrow.

**Comment by oldcookie** [comment] 2015-06-17 15:48
So here's a capture of what happens.  I was wrong in the descriptions, it's actually `i-playlist.mediaSequence` being greater than the length of the `playlist.segments`.  

![screen shot 2015-06-17 at 11 43 33 am](https://cloud.githubusercontent.com/assets/746271/8211763/529a7fac-14e6-11e5-8030-22d117b5fbe5.png)

Would a simple check of light of segments fix this?

**Comment by vdeshpande** [comment] 2015-06-17 22:08
Hi @oldcookie ,

I stepped through the code for the playlist.js file using a sample live stream however I did not get a value of undefined on segment while letting the live stream play.

Are you able to point me to a page where this condition is met and can be reproduced on a regular basis ?

**Comment by oldcookie** [comment] 2015-06-18 14:56
Don't have one readily available, I'm just testing with our test server locally.  The stream is a live RTMP stream transcoded to HLS by Wowza.   Let me see if I can put something up on EC2 that can replicate this.

One question, is this potentially an issue with the way Wowza or us is doing the transcoding?

**Comment by vdeshpande** [comment] 2015-06-18 15:19
It would be difficult to say anything unless the I can see the issue and which is reproducible at a fairly constant rate.

One thing which I have observed , which I'll share is this:
While testing locally as well, if I put in breakpoints on the lines of code which you had mentioned earlier, and if I let the live stream play and immediately pause it, and try debugging and stepping through the code using the browser tools until we get to the point where all the segments obtained till that point have been exhausted, the error of undefined on the segment gets thrown which seems logical to me since we don't have any further segments to get.

Otherwise if I let the LIVE stream play in the player the issue does not seem to occur.

**Comment by oldcookie** [comment] 2015-06-18 17:43
Ok, I have a stream running on this url that has this problem: http://54.147.189.132/yanked/comic-con/playlist.m3u8

Hopefully it stays up until you guys get to check it. :)

If you point example.html to it, run it for a while, you should see the issue.  It's been happening pretty consistently for me.

**Comment by dmlap** [comment] 2015-06-19 14:37
@oldcookie I was able to check your stream out this morning and hit the error after about 5 minutes of playback. The root exception occurred because segmentsDuration() was getting called with an `endSequence` number that was greater than the media sequence of the last available segment in the playlist. That shouldn't happen under normal operation though, so I dug a little deeper.

On my play through, I actually missed a whole segment between playlist refreshes and that caused the expired segment duration calculation to pass a bad value through to segmentsDuration(). That is, the player had been playing a playlist with mediaSequence 35532 and three segments available and after refreshing, it received a playlist with mediaSequence 35536 and three segments available. Segment 35535 was missed entirely so the two playlists couldn't be synced up and the bad values got pushed into segmentsDuration().

In this case though, I believe the problem is with your Wowza setup. The HLS spec asserts that streaming servers [must not remove segments from the media playlist](https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-6.2.2) unless there is greater than three target duration's worth of segments available. With a 5 second target duration like you have setup, you should have greater than 15 seconds of content in each playlist response. In my play through the playlist responses I saw were about 5 seconds of total content.

I'm not familiar with Wowza's HLS settings but if there's a way to bump up the window size to at least 30 seconds of content, your stream should be much more stable. Also, I'd consider making your target duration a bit larger if that's easy. I think Apple's current recommendation is 9 second target durations.

**Comment by oldcookie** [comment] 2015-06-22 18:53
Our configure is shorter than the recommended, in that chunk duration is set to 2s and playlist chunk count is set to 3, so about a 6s worth of content.  We set it like this to reduce latency.   Will test the longer duration and report back.

**Comment by oldcookie** [comment] 2015-06-22 22:04
So we've dug more into the way Wowza works.  Looks like Wowza changes the target duration based on the longest gap between keyframes.  So even though we set target duration to 2s, if keyframe rate drops to 5s per keyframe, it would change the target duration to 5s.   So we suspect that the content size in each playlist is not changing by the target duration was changed, and hence creating this issue.

**Comment by dmlap** [comment] 2015-06-23 01:15
Interesting! Thanks for following up with the details. I'm going to close this one based on the info we have so far but feel free to re-open if anything new comes to light.

I understand trying to reduce live latency but I would consider bumping the live window size a bit. Six seconds is not a lot of wiggle room if there are delays publishing the segments or m3u8 updates.

**Closed by dmlap** 2015-06-23 01:15 UTC
